<?php

namespace Modules\Sf\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class SfLandingsiteTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Model::unguard();

        DB::table('sf_landingsite')->insert(array (
            0 =>
            array (
                'id' => 1,
                'LandingSiteID' => 'GL',
                'LandingSiteName' => 'Galle',
                'Longitude' => '80.229237',
                'Latitude' => '6.034017',
                'LongLat' => '6.034016868625014,80.22923734547471',
                'countryCode' => '1',
                'LandingSiteImage' => NULL,
                'list_index' => 1,
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            1 =>
            array (
                'id' => 2,
                'LandingSiteID' => 'NG',
                'LandingSiteName' => 'Negombo',
                'Longitude' => '79.827081',
                'Latitude' => '7.218908',
                'LongLat' => '7.218908158747213, 79.82708115128725',
                'countryCode' => '1',
                'LandingSiteImage' => NULL,
                'list_index' => 2,
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            2 =>
            array (
                'id' => 3,
                'LandingSiteID' => 'DK',
                'LandingSiteName' => 'Dikovita',
                'Longitude' => '79.866158',
                'Latitude' => '7.005527',
                'LongLat' => '7.005527232315951,79.86615764749695',
                'countryCode' => '1',
                'LandingSiteImage' => NULL,
                'list_index' => 3,
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            3 =>
            array (
                'id' => 4,
                'LandingSiteID' => 'TC',
                'LandingSiteName' => 'Trincomalee',
                'Longitude' => '81.243411',
                'Latitude' => '8.544565',
                'LongLat' => '8.54456474133872,81.24341087015156',
                'countryCode' => '1',
                'LandingSiteImage' => NULL,
                'list_index' => 4,
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            4 =>
            array (
                'id' => 5,
                'LandingSiteID' => 'NW',
                'LandingSiteName' => 'Nilwella',
                'Longitude' => '80.718551',
                'Latitude' => '5.966139',
                'LongLat' => '5.966139080908945,80.71855077681191',
                'countryCode' => '1',
                'LandingSiteImage' => NULL,
                'list_index' => 5,
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            5 =>
            array (
                'id' => 6,
                'LandingSiteID' => 'GD',
                'LandingSiteName' => 'Gandara',
                'Longitude' => '80.618034',
                'Latitude' => '5.937880',
                'LongLat' => '5.9378797809502,80.61803441278528',
                'countryCode' => '1',
                'LandingSiteImage' => NULL,
                'list_index' => 6,
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            6 =>
            array (
                'id' => 7,
                'LandingSiteID' => 'HB',
                'LandingSiteName' => 'Hambantota',
                'Longitude' => '81.127602',
                'Latitude' => '6.125392',
                'LongLat' => '6.125392397252996,81.12760244668353',
                'countryCode' => '1',
                'LandingSiteImage' => NULL,
                'list_index' => 7,
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            7 =>
            array (
                'id' => 8,
                'LandingSiteID' => 'KR',
                'LandingSiteName' => 'Kirinda',
                'Longitude' => '81.337947',
                'Latitude' => '6.216024',
                'LongLat' => '6.2160237417822515,81.33794700580026',
                'countryCode' => '1',
                'LandingSiteImage' => NULL,
                'list_index' => 8,
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            8 =>
            array (
                'id' => 9,
                'LandingSiteID' => 'DN',
                'LandingSiteName' => 'Dondra',
                'Longitude' => '80.582648',
                'Latitude' => '5.924586',
                'LongLat' => '5.9245858891928,80.58264774323898',
                'countryCode' => '1',
                'LandingSiteImage' => NULL,
                'list_index' => 9,
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            9 =>
            array (
                'id' => 10,
                'LandingSiteID' => 'CH',
                'LandingSiteName' => 'Chilaw',
                'Longitude' => '79.791261',
                'Latitude' => '7.579889',
                'LongLat' => '7.579889186572221,79.79126113921038',
                'countryCode' => '1',
                'LandingSiteImage' => NULL,
                'list_index' => 10,
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            10 =>
            array (
                'id' => 11,
                'LandingSiteID' => 'PP',
                'LandingSiteName' => 'Point Pedro',
                'Longitude' => '80.235299',
                'Latitude' => '9.828618',
                'LongLat' => '9.828618,80.235299',
                'countryCode' => '1',
                'LandingSiteImage' => NULL,
                'list_index' => 11,
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            11 =>
            array (
                'id' => 12,
                'LandingSiteID' => 'KU',
                'LandingSiteName' => 'Kudawella',
                'Longitude' => '80.733193',
                'Latitude' => '5.977310',
                'LongLat' => '5.977309757667339,80.73319314385306',
                'countryCode' => '1',
                'LandingSiteImage' => NULL,
                'list_index' => 12,
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            12 =>
            array (
                'id' => 13,
                'LandingSiteID' => 'MI',
                'LandingSiteName' => 'Mirissa',
                'Longitude' => '80.450204',
                'Latitude' => '5.948369',
                'LongLat' => '5.948369417108844,80.45020356784298',
                'countryCode' => '1',
                'LandingSiteImage' => NULL,
                'list_index' => 13,
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            13 =>
            array (
                'id' => 14,
                'LandingSiteID' => 'KP',
                'LandingSiteName' => 'Kalpitiya',
                'Longitude' => '79.767204',
                'Latitude' => '8.237536',
                'LongLat' => '8.237536456967732,79.76720398292882',
                'countryCode' => '1',
                'LandingSiteImage' => NULL,
                'list_index' => 14,
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            14 =>
            array (
                'id' => 15,
                'LandingSiteID' => 'BR',
                'LandingSiteName' => 'Beruwala',
                'Longitude' => '79.978645',
                'Latitude' => '6.472293',
                'LongLat' => '6.4722926090822614,79.9786451675731',
                'countryCode' => '1',
                'LandingSiteImage' => NULL,
                'list_index' => 15,
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            15 =>
            array (
                'id' => 16,
                'LandingSiteID' => 'WL',
                'LandingSiteName' => 'Walachchenei',
                'Longitude' => '81.530130',
                'Latitude' => '7.927736',
                'LongLat' => '7.927735673166781,81.53012975951847',
                'countryCode' => '1',
                'LandingSiteImage' => NULL,
                'list_index' => 16,
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            16 =>
            array (
                'id' => 17,
                'LandingSiteID' => 'SU',
                'LandingSiteName' => 'Suduwella',
                'Longitude' => '80.641394',
                'Latitude' => '5.946376',
                'LongLat' => '5.946375660106851,80.64139423900758',
                'countryCode' => '1',
                'LandingSiteImage' => NULL,
                'list_index' => 17,
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            17 =>
            array (
                'id' => 18,
                'LandingSiteID' => 'TG',
                'LandingSiteName' => 'Tangalle',
                'Longitude' => '80.798321',
                'Latitude' => '6.024575',
                'LongLat' => '6.024575395178619,80.79832107238022',
                'countryCode' => '1',
                'LandingSiteImage' => NULL,
                'list_index' => 18,
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            18 =>
            array (
                'id' => 19,
                'LandingSiteID' => 'OL',
                'LandingSiteName' => 'Oluvil',
                'Longitude' => '81.865218',
                'Latitude' => '7.274941',
                'LongLat' => '7.274941318226901,81.86521751170848',
                'countryCode' => '1',
                'LandingSiteImage' => NULL,
                'list_index' => 19,
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            19 =>
            array (
                'id' => 20,
                'LandingSiteID' => 'KT',
                'LandingSiteName' => 'Kottegoda',
                'Longitude' => '80.641327',
                'Latitude' => '5.947523',
                'LongLat' => '5.947522982010185,80.64132713008314',
                'countryCode' => '1',
                'LandingSiteImage' => NULL,
                'list_index' => 20,
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            20 =>
            array (
                'id' => 21,
                'LandingSiteID' => 'JF',
                'LandingSiteName' => 'Jaffna',
                'Longitude' => '80.013537',
                'Latitude' => '9.653743',
                'LongLat' => '9.653743,80.013537',
                'countryCode' => '1',
                'LandingSiteImage' => NULL,
                'list_index' => 21,
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
        ));
    }
}
