<?php

namespace Modules\Settings\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use Modules\Settings\Entities\Country;

class CountrySeederTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Model::unguard();

        $object= [
            ['id' => 1, 'country_code'=>'AF','country_name'=>'Afghanistan', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+04:30'],
            ['id' => 2, 'country_code'=>'AX','country_name'=>'Åland Islands', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+02:00'],
            ['id' => 3, 'country_code'=>'AL','country_name'=>'Albania', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+01:00'],
            ['id' => 4, 'country_code'=>'DZ','country_name'=>'Algeria', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+01:00'],
            ['id' => 5, 'country_code'=>'AS','country_name'=>'American Samoa', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-11:00'],
            ['id' => 6, 'country_code'=>'AD','country_name'=>'Andorra', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+01:00'],
            ['id' => 7, 'country_code'=>'AO','country_name'=>'Angola', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+01:00'],
            ['id' => 8, 'country_code'=>'AI','country_name'=>'Anguilla', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-04:00'],
            ['id' => 9, 'country_code'=>'AQ','country_name'=>'Antarctica', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-03:00'],
            ['id' => 10, 'country_code'=>'AG','country_name'=>'Antigua and Barbuda', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-04:00'],
            ['id' => 11, 'country_code'=>'AR','country_name'=>'Argentina', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-03:00'],
            ['id' => 12, 'country_code'=>'AM','country_name'=>'Armenia', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+04:00'],
            ['id' => 13, 'country_code'=>'AW','country_name'=>'Aruba', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-04:00'],
            ['id' => 14, 'country_code'=>'AU','country_name'=>'Australia', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+10:00'],
            ['id' => 15, 'country_code'=>'AT','country_name'=>'Austria', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+01:00'],
            ['id' => 16, 'country_code'=>'AZ','country_name'=>'Azerbaijan', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+04:00'],
            ['id' => 17, 'country_code'=>'BS','country_name'=>'Bahamas, The', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-05:00'],
            ['id' => 18, 'country_code'=>'BH','country_name'=>'Bahrain', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+03:00'],
            ['id' => 19, 'country_code'=>'BD','country_name'=>'Bangladesh', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+06:00'],
            ['id' => 20, 'country_code'=>'BB','country_name'=>'Barbados', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-04:00'],
            ['id' => 21, 'country_code'=>'BY','country_name'=>'Belarus', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+03:00'],
            ['id' => 22, 'country_code'=>'BE','country_name'=>'Belgium', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+01:00'],
            ['id' => 23, 'country_code'=>'BZ','country_name'=>'Belize', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-06:00'],
            ['id' => 24, 'country_code'=>'BJ','country_name'=>'Benin', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+01:00'],
            ['id' => 25, 'country_code'=>'BM','country_name'=>'Bermuda', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-04:00'],
            ['id' => 26, 'country_code'=>'BT','country_name'=>'Bhutan', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+06:00'],
            ['id' => 27, 'country_code'=>'VE','country_name'=>'Bolivarian Republic of Venezuela', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-04:30'],
            ['id' => 28, 'country_code'=>'BO','country_name'=>'Bolivia', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-04:00'],
            ['id' => 29, 'country_code'=>'BQ','country_name'=>'Bonaire, Sint Eustatius and Saba', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-04:00'],
            ['id' => 30, 'country_code'=>'BA','country_name'=>'Bosnia and Herzegovina', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+01:00'],
            ['id' => 31, 'country_code'=>'BW','country_name'=>'Botswana', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+02:00'],
            ['id' => 32, 'country_code'=>'BV','country_name'=>'Bouvet Island', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT'],
            ['id' => 33, 'country_code'=>'BR','country_name'=>'Brazil', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-03:00'],
            ['id' => 34, 'country_code'=>'IO','country_name'=>'British Indian Ocean Territory', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+06:00'],
            ['id' => 35, 'country_code'=>'BN','country_name'=>'Brunei', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+08:00'],
            ['id' => 36, 'country_code'=>'BG','country_name'=>'Bulgaria', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+02:00'],
            ['id' => 37, 'country_code'=>'BF','country_name'=>'Burkina Faso', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT'],
            ['id' => 38, 'country_code'=>'BI','country_name'=>'Burundi', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+02:00'],
            ['id' => 39, 'country_code'=>'CV','country_name'=>'Cabo Verde', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-01:00'],
            ['id' => 40, 'country_code'=>'KH','country_name'=>'Cambodia', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+07:00'],
            ['id' => 41, 'country_code'=>'CM','country_name'=>'Cameroon', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+01:00'],
            ['id' => 42, 'country_code'=>'CA','country_name'=>'Canada', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-05:00'],
            ['id' => 43, 'country_code'=>'KY','country_name'=>'Cayman Islands', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-05:00'],
            ['id' => 44, 'country_code'=>'CF','country_name'=>'Central African Republic', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+01:00'],
            ['id' => 45, 'country_code'=>'TD','country_name'=>'Chad', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+01:00'],
            ['id' => 46, 'country_code'=>'CL','country_name'=>'Chile', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-03:00'],
            ['id' => 47, 'country_code'=>'CN','country_name'=>'China', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+08:00'],
            ['id' => 48, 'country_code'=>'CX','country_name'=>'Christmas Island', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+07:00'],
            ['id' => 49, 'country_code'=>'CC','country_name'=>'Cocos (Keeling) Islands', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+06:30'],
            ['id' => 50, 'country_code'=>'CO','country_name'=>'Colombia', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-05:00'],
            ['id' => 51, 'country_code'=>'KM','country_name'=>'Comoros', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+03:00'],
            ['id' => 52, 'country_code'=>'CG','country_name'=>'Congo', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+01:00'],
            ['id' => 53, 'country_code'=>'CD','country_name'=>'Congo (DRC)', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+01:00'],
            ['id' => 54, 'country_code'=>'CK','country_name'=>'Cook Islands', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-10:00'],
            ['id' => 55, 'country_code'=>'CR','country_name'=>'Costa Rica', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-06:00'],
            ['id' => 56, 'country_code'=>'CI','country_name'=>'Côte dIvoire', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT'],
            ['id' => 57, 'country_code'=>'HR','country_name'=>'Croatia', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+01:00'],
            ['id' => 58, 'country_code'=>'CU','country_name'=>'Cuba', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-05:00'],
            ['id' => 59, 'country_code'=>'CW','country_name'=>'Curaçao', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-04:00'],
            ['id' => 60, 'country_code'=>'CY','country_name'=>'Cyprus', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+02:00'],
            ['id' => 61, 'country_code'=>'CZ','country_name'=>'Czech Republic', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+01:00'],
            ['id' => 62, 'country_code'=>'TL','country_name'=>'Democratic Republic of Timor-Leste', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+09:00'],
            ['id' => 63, 'country_code'=>'DK','country_name'=>'Denmark', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+01:00'],
            ['id' => 64, 'country_code'=>'DJ','country_name'=>'Djibouti', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+03:00'],
            ['id' => 65, 'country_code'=>'DM','country_name'=>'Dominica', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-04:00'],
            ['id' => 66, 'country_code'=>'DO','country_name'=>'Dominican Republic', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-04:00'],
            ['id' => 67, 'country_code'=>'EC','country_name'=>'Ecuador', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-05:00'],
            ['id' => 68, 'country_code'=>'EG','country_name'=>'Egypt', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+02:00'],
            ['id' => 69, 'country_code'=>'SV','country_name'=>'El Salvador', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-06:00'],
            ['id' => 70, 'country_code'=>'GQ','country_name'=>'Equatorial Guinea', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+01:00'],
            ['id' => 71, 'country_code'=>'ER','country_name'=>'Eritrea', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+03:00'],
            ['id' => 72, 'country_code'=>'EE','country_name'=>'Estonia', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+02:00'],
            ['id' => 73, 'country_code'=>'ET','country_name'=>'Ethiopia', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+03:00'],
            ['id' => 74, 'country_code'=>'FK','country_name'=>'Falkland Islands (Islas Malvinas)', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-03:00'],
            ['id' => 75, 'country_code'=>'FO','country_name'=>'Faroe Islands', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT'],
            ['id' => 76, 'country_code'=>'FJ','country_name'=>'Fiji Islands', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+12:00'],
            ['id' => 77, 'country_code'=>'FI','country_name'=>'Finland', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+02:00'],
            ['id' => 78, 'country_code'=>'FR','country_name'=>'France', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+01:00'],
            ['id' => 79, 'country_code'=>'GF','country_name'=>'French Guiana', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-03:00'],
            ['id' => 80, 'country_code'=>'PF','country_name'=>'French Polynesia', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-10:00'],
            ['id' => 81, 'country_code'=>'TF','country_name'=>'French Southern and Antarctic Lands', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+05:00'],
            ['id' => 82, 'country_code'=>'GA','country_name'=>'Gabon', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+01:00'],
            ['id' => 83, 'country_code'=>'GM','country_name'=>'Gambia, The', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT'],
            ['id' => 84, 'country_code'=>'GE','country_name'=>'Georgia', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+04:00'],
            ['id' => 85, 'country_code'=>'DE','country_name'=>'Germany', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+01:00'],
            ['id' => 86, 'country_code'=>'GH','country_name'=>'Ghana', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT'],
            ['id' => 87, 'country_code'=>'GI','country_name'=>'Gibraltar', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+01:00'],
            ['id' => 88, 'country_code'=>'GR','country_name'=>'Greece', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+02:00'],
            ['id' => 89, 'country_code'=>'GL','country_name'=>'Greenland', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-03:00'],
            ['id' => 90, 'country_code'=>'GD','country_name'=>'Grenada', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-04:00'],
            ['id' => 91, 'country_code'=>'GP','country_name'=>'Guadeloupe', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-04:00'],
            ['id' => 92, 'country_code'=>'GU','country_name'=>'Guam', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+10:00'],
            ['id' => 93, 'country_code'=>'GT','country_name'=>'Guatemala', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-06:00'],
            ['id' => 94, 'country_code'=>'GG','country_name'=>'Guernsey', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT'],
            ['id' => 95, 'country_code'=>'GN','country_name'=>'Guinea', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT'],
            ['id' => 96, 'country_code'=>'GW','country_name'=>'Guinea-Bissau', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT'],
            ['id' => 97, 'country_code'=>'GY','country_name'=>'Guyana', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-04:00'],
            ['id' => 98, 'country_code'=>'HT','country_name'=>'Haiti', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-05:00'],
            ['id' => 99, 'country_code'=>'HM','country_name'=>'Heard Island and McDonald Islands', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+04:00'],
            ['id' => 100, 'country_code'=>'HN','country_name'=>'Honduras', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-06:00'],
            ['id' => 101, 'country_code'=>'HK','country_name'=>'Hong Kong SAR', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+08:00'],
            ['id' => 102, 'country_code'=>'HU','country_name'=>'Hungary', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+01:00'],
            ['id' => 103, 'country_code'=>'IS','country_name'=>'Iceland', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT'],
            ['id' => 104, 'country_code'=>'IN','country_name'=>'India', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+05:30'],
            ['id' => 105, 'country_code'=>'ID','country_name'=>'Indonesia', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+07:00'],
            ['id' => 106, 'country_code'=>'IR','country_name'=>'Iran', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+03:30'],
            ['id' => 107, 'country_code'=>'IQ','country_name'=>'Iraq', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+03:00'],
            ['id' => 108, 'country_code'=>'IE','country_name'=>'Ireland', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT'],
            ['id' => 109, 'country_code'=>'IL','country_name'=>'Israel', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+02:00'],
            ['id' => 110, 'country_code'=>'IT','country_name'=>'Italy', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+01:00'],
            ['id' => 111, 'country_code'=>'JM','country_name'=>'Jamaica', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-05:00'],
            ['id' => 112, 'country_code'=>'SJ','country_name'=>'Jan Mayen', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+01:00'],
            ['id' => 113, 'country_code'=>'JP','country_name'=>'Japan', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+09:00'],
            ['id' => 114, 'country_code'=>'JE','country_name'=>'Jersey', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT'],
            ['id' => 115, 'country_code'=>'JO','country_name'=>'Jordan', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+02:00'],
            ['id' => 116, 'country_code'=>'KZ','country_name'=>'Kazakhstan', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+06:00'],
            ['id' => 117, 'country_code'=>'KE','country_name'=>'Kenya', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+03:00'],
            ['id' => 118, 'country_code'=>'KI','country_name'=>'Kiribati', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+12:00'],
            ['id' => 119, 'country_code'=>'KR','country_name'=>'Korea', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+09:00'],
            ['id' => 120, 'country_code'=>'XK','country_name'=>'Kosovo', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+01:00'],
            ['id' => 121, 'country_code'=>'KW','country_name'=>'Kuwait', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+03:00'],
            ['id' => 122, 'country_code'=>'KG','country_name'=>'Kyrgyzstan', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+06:00'],
            ['id' => 123, 'country_code'=>'LA','country_name'=>'Laos', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+07:00'],
            ['id' => 124, 'country_code'=>'LV','country_name'=>'Latvia', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+02:00'],
            ['id' => 125, 'country_code'=>'LB','country_name'=>'Lebanon', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+02:00'],
            ['id' => 126, 'country_code'=>'LS','country_name'=>'Lesotho', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+02:00'],
            ['id' => 127, 'country_code'=>'LR','country_name'=>'Liberia', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT'],
            ['id' => 128, 'country_code'=>'LY','country_name'=>'Libya', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+02:00'],
            ['id' => 129, 'country_code'=>'LI','country_name'=>'Liechtenstein', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+01:00'],
            ['id' => 130, 'country_code'=>'LT','country_name'=>'Lithuania', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+02:00'],
            ['id' => 131, 'country_code'=>'LU','country_name'=>'Luxembourg', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+01:00'],
            ['id' => 132, 'country_code'=>'MO','country_name'=>'Macao SAR', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+08:00'],
            ['id' => 133, 'country_code'=>'MK','country_name'=>'Macedonia, Former Yugoslav Republic of', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+01:00'],
            ['id' => 134, 'country_code'=>'MG','country_name'=>'Madagascar', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+03:00'],
            ['id' => 135, 'country_code'=>'MW','country_name'=>'Malawi', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+02:00'],
            ['id' => 136, 'country_code'=>'MY','country_name'=>'Malaysia', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+08:00'],
            ['id' => 137, 'country_code'=>'MV','country_name'=>'Maldives', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+05:00'],
            ['id' => 138, 'country_code'=>'ML','country_name'=>'Mali', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT'],
            ['id' => 139, 'country_code'=>'MT','country_name'=>'Malta', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+01:00'],
            ['id' => 140, 'country_code'=>'IM','country_name'=>'Man, Isle of', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT'],
            ['id' => 141, 'country_code'=>'MH','country_name'=>'Marshall Islands', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+12:00'],
            ['id' => 142, 'country_code'=>'MQ','country_name'=>'Martinique', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-04:00'],
            ['id' => 143, 'country_code'=>'MR','country_name'=>'Mauritania', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT'],
            ['id' => 144, 'country_code'=>'MU','country_name'=>'Mauritius', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+04:00'],
            ['id' => 145, 'country_code'=>'YT','country_name'=>'Mayotte', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+03:00'],
            ['id' => 146, 'country_code'=>'MX','country_name'=>'Mexico', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-06:00'],
            ['id' => 147, 'country_code'=>'FM','country_name'=>'Micronesia', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+10:00'],
            ['id' => 148, 'country_code'=>'MD','country_name'=>'Moldova', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+02:00'],
            ['id' => 149, 'country_code'=>'MC','country_name'=>'Monaco', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+01:00'],
            ['id' => 150, 'country_code'=>'MN','country_name'=>'Mongolia', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+08:00'],
            ['id' => 151, 'country_code'=>'ME','country_name'=>'Montenegro', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+01:00'],
            ['id' => 152, 'country_code'=>'MS','country_name'=>'Montserrat', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-04:00'],
            ['id' => 153, 'country_code'=>'MA','country_name'=>'Morocco', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT'],
            ['id' => 154, 'country_code'=>'MZ','country_name'=>'Mozambique', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+02:00'],
            ['id' => 155, 'country_code'=>'MM','country_name'=>'Myanmar', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+06:30'],
            ['id' => 156, 'country_code'=>'NA','country_name'=>'Namibia', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+01:00'],
            ['id' => 157, 'country_code'=>'NR','country_name'=>'Nauru', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+12:00'],
            ['id' => 158, 'country_code'=>'NP','country_name'=>'Nepal', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+05:45'],
            ['id' => 159, 'country_code'=>'NL','country_name'=>'Netherlands', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+01:00'],
            ['id' => 160, 'country_code'=>'NC','country_name'=>'New Caledonia', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+11:00'],
            ['id' => 161, 'country_code'=>'NZ','country_name'=>'New Zealand', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+12:00'],
            ['id' => 162, 'country_code'=>'NI','country_name'=>'Nicaragua', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-06:00'],
            ['id' => 163, 'country_code'=>'NE','country_name'=>'Niger', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+01:00'],
            ['id' => 164, 'country_code'=>'NG','country_name'=>'Nigeria', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+01:00'],
            ['id' => 165, 'country_code'=>'NU','country_name'=>'Niue', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-11:00'],
            ['id' => 166, 'country_code'=>'NF','country_name'=>'Norfolk Island', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+11:00'],
            ['id' => 167, 'country_code'=>'KP','country_name'=>'North Korea', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+09:00'],
            ['id' => 168, 'country_code'=>'MP','country_name'=>'Northern Mariana Islands', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+10:00'],
            ['id' => 169, 'country_code'=>'NO','country_name'=>'Norway', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+01:00'],
            ['id' => 170, 'country_code'=>'OM','country_name'=>'Oman', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+04:00'],
            ['id' => 171, 'country_code'=>'PK','country_name'=>'Pakistan', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+05:00'],
            ['id' => 172, 'country_code'=>'PW','country_name'=>'Palau', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+09:00'],
            ['id' => 173, 'country_code'=>'PS','country_name'=>'Palestinian Authority', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+02:00'],
            ['id' => 174, 'country_code'=>'PA','country_name'=>'Panama', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-05:00'],
            ['id' => 175, 'country_code'=>'PG','country_name'=>'Papua New Guinea', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+10:00'],
            ['id' => 176, 'country_code'=>'PY','country_name'=>'Paraguay', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-04:00'],
            ['id' => 177, 'country_code'=>'PE','country_name'=>'Peru', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-05:00'],
            ['id' => 178, 'country_code'=>'PH','country_name'=>'Philippines', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+08:00'],
            ['id' => 179, 'country_code'=>'PN','country_name'=>'Pitcairn Islands', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-08:00'],
            ['id' => 180, 'country_code'=>'PL','country_name'=>'Poland', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+01:00'],
            ['id' => 181, 'country_code'=>'PT','country_name'=>'Portugal', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT'],
            ['id' => 182, 'country_code'=>'PR','country_name'=>'Puerto Rico', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-04:00'],
            ['id' => 183, 'country_code'=>'QA','country_name'=>'Qatar', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+03:00'],
            ['id' => 184, 'country_code'=>'RE','country_name'=>'Reunion', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+04:00'],
            ['id' => 185, 'country_code'=>'RO','country_name'=>'Romania', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+02:00'],
            ['id' => 186, 'country_code'=>'RU','country_name'=>'Russia', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+03:00'],
            ['id' => 187, 'country_code'=>'RW','country_name'=>'Rwanda', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+02:00'],
            ['id' => 188, 'country_code'=>'BL','country_name'=>'Saint Barthélemy', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-04:00'],
            ['id' => 189, 'country_code'=>'SH','country_name'=>'Saint Helena, Ascension and Tristan da Cunha', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT'],
            ['id' => 190, 'country_code'=>'KN','country_name'=>'Saint Kitts and Nevis', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-04:00'],
            ['id' => 191, 'country_code'=>'LC','country_name'=>'Saint Lucia', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-04:00'],
            ['id' => 192, 'country_code'=>'MF','country_name'=>'Saint Martin (French part)', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-04:00'],
            ['id' => 193, 'country_code'=>'PM','country_name'=>'Saint Pierre and Miquelon', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-03:00'],
            ['id' => 194, 'country_code'=>'VC','country_name'=>'Saint Vincent and the Grenadines', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-04:00'],
            ['id' => 195, 'country_code'=>'WS','country_name'=>'Samoa', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+13:00'],
            ['id' => 196, 'country_code'=>'SM','country_name'=>'San Marino', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+01:00'],
            ['id' => 197, 'country_code'=>'ST','country_name'=>'São Tomé and Príncipe', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT'],
            ['id' => 198, 'country_code'=>'SA','country_name'=>'Saudi Arabia', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+03:00'],
            ['id' => 199, 'country_code'=>'SN','country_name'=>'Senegal', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT'],
            ['id' => 200, 'country_code'=>'RS','country_name'=>'Serbia', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+01:00'],
            ['id' => 201, 'country_code'=>'SC','country_name'=>'Seychelles', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+04:00'],
            ['id' => 202, 'country_code'=>'SL','country_name'=>'Sierra Leone', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT'],
            ['id' => 203, 'country_code'=>'SG','country_name'=>'Singapore', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+08:00'],
            ['id' => 204, 'country_code'=>'SX','country_name'=>'Sint Maarten (Dutch part)', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-04:00'],
            ['id' => 205, 'country_code'=>'SK','country_name'=>'Slovakia', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+01:00'],
            ['id' => 206, 'country_code'=>'SI','country_name'=>'Slovenia', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+01:00'],
            ['id' => 207, 'country_code'=>'SB','country_name'=>'Solomon Islands', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+11:00'],
            ['id' => 208, 'country_code'=>'SO','country_name'=>'Somalia', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+03:00'],
            ['id' => 209, 'country_code'=>'ZA','country_name'=>'South Africa', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+02:00'],
            ['id' => 210, 'country_code'=>'GS','country_name'=>'South Georgia and the South Sandwich Islands', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-02:00'],
            ['id' => 211, 'country_code'=>'SS','country_name'=>'South Sudan', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+03:00'],
            ['id' => 212, 'country_code'=>'ES','country_name'=>'Spain', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+01:00'],
            ['id' => 213, 'country_code'=>'LK','country_name'=>'Sri Lanka', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+05:30'],
            ['id' => 214, 'country_code'=>'SD','country_name'=>'Sudan', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+03:00'],
            ['id' => 215, 'country_code'=>'SR','country_name'=>'Suriname', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-03:00'],
            ['id' => 216, 'country_code'=>'SJ','country_name'=>'Svalbard', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+01:00'],
            ['id' => 217, 'country_code'=>'SZ','country_name'=>'Swaziland', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+02:00'],
            ['id' => 218, 'country_code'=>'SE','country_name'=>'Sweden', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+01:00'],
            ['id' => 219, 'country_code'=>'CH','country_name'=>'Switzerland', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+01:00'],
            ['id' => 220, 'country_code'=>'SY','country_name'=>'Syria', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+02:00'],
            ['id' => 221, 'country_code'=>'TW','country_name'=>'Taiwan', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+08:00'],
            ['id' => 222, 'country_code'=>'TJ','country_name'=>'Tajikistan', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+05:00'],
            ['id' => 223, 'country_code'=>'TZ','country_name'=>'Tanzania', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+03:00'],
            ['id' => 224, 'country_code'=>'TH','country_name'=>'Thailand', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+07:00'],
            ['id' => 225, 'country_code'=>'TG','country_name'=>'Togo', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT'],
            ['id' => 226, 'country_code'=>'TK','country_name'=>'Tokelau', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+13:00'],
            ['id' => 227, 'country_code'=>'TO','country_name'=>'Tonga', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+13:00'],
            ['id' => 228, 'country_code'=>'TT','country_name'=>'Trinidad and Tobago', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-04:00'],
            ['id' => 229, 'country_code'=>'TN','country_name'=>'Tunisia', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+01:00'],
            ['id' => 230, 'country_code'=>'TR','country_name'=>'Turkey', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+02:00'],
            ['id' => 231, 'country_code'=>'TM','country_name'=>'Turkmenistan', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+05:00'],
            ['id' => 232, 'country_code'=>'TC','country_name'=>'Turks and Caicos Islands', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-05:00'],
            ['id' => 233, 'country_code'=>'TV','country_name'=>'Tuvalu', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+12:00'],
            ['id' => 234, 'country_code'=>'UM','country_name'=>'U.S. Minor Outlying Islands', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-11:00'],
            ['id' => 235, 'country_code'=>'UG','country_name'=>'Uganda', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+03:00'],
            ['id' => 236, 'country_code'=>'UA','country_name'=>'Ukraine', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+02:00'],
            ['id' => 237, 'country_code'=>'AE','country_name'=>'United Arab Emirates', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+04:00'],
            ['id' => 238, 'country_code'=>'GB','country_name'=>'United Kingdom', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT'],
            ['id' => 239, 'country_code'=>'US','country_name'=>'United States', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-07:00'],
            ['id' => 240, 'country_code'=>'US','country_name'=>'United States', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-08:00'],
            ['id' => 241, 'country_code'=>'UY','country_name'=>'Uruguay', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-03:00'],
            ['id' => 242, 'country_code'=>'UZ','country_name'=>'Uzbekistan', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+05:00'],
            ['id' => 243, 'country_code'=>'VU','country_name'=>'Vanuatu', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+11:00'],
            ['id' => 244, 'country_code'=>'VA','country_name'=>'Vatican City', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+01:00'],
            ['id' => 245, 'country_code'=>'VN','country_name'=>'Vietnam', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+07:00'],
            ['id' => 246, 'country_code'=>'VI','country_name'=>'Virgin Islands, U.S.', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-04:00'],
            ['id' => 247, 'country_code'=>'VG','country_name'=>'Virgin Islands, British', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT-04:00'],
            ['id' => 248, 'country_code'=>'WF','country_name'=>'Wallis and Futuna', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+12:00'],
            ['id' => 249, 'country_code'=>'YE','country_name'=>'Yemen', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+03:00'],
            ['id' => 250, 'country_code'=>'ZM','country_name'=>'Zambia', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+02:00'],
            ['id' => 251, 'country_code'=>'ZW','country_name'=>'Zimbabwe', 'date_format'=>'YYYY-MM-DD', 'created_by'=>'Migrations',  'list_index'=>1, 'time_zone'=>'GMT+02:00'],
        ];
        Country::insert($object);
    }
}
