<?php

namespace Modules\Settings\Database\Seeders;

use Illuminate\Database\Seeder;

class SettingsLanguagesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('settings_languages')->delete();
        
        \DB::table('settings_languages')->insert(array (
            0 => 
            array (
                'langcode' => 'ab',
                'name' => 'Abkhaz',
                'nativeName' => 'аҧсуа',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            1 => 
            array (
                'langcode' => 'aa',
                'name' => 'Afar',
                'nativeName' => 'Afaraf',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            2 => 
            array (
                'langcode' => 'af',
                'name' => 'Afrikaans',
                'nativeName' => 'Afrikaans',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            3 => 
            array (
                'langcode' => 'ak',
                'name' => 'Akan',
                'nativeName' => 'Akan',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            4 => 
            array (
                'langcode' => 'sq',
                'name' => 'Albanian',
                'nativeName' => 'Shqip',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            5 => 
            array (
                'langcode' => 'am',
                'name' => 'Amharic',
                'nativeName' => 'አማርኛ',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            6 => 
            array (
                'langcode' => 'ar',
                'name' => 'Arabic',
                'nativeName' => 'العربية',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            7 => 
            array (
                'langcode' => 'an',
                'name' => 'Aragonese',
                'nativeName' => 'Aragonés',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            8 => 
            array (
                'langcode' => 'hy',
                'name' => 'Armenian',
                'nativeName' => 'Հայերեն',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            9 => 
            array (
                'langcode' => 'as',
                'name' => 'Assamese',
                'nativeName' => 'অসমীয়া',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            10 => 
            array (
                'langcode' => 'av',
                'name' => 'Avaric',
                'nativeName' => 'авар мацӀ, магӀарул мацӀ',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            11 => 
            array (
                'langcode' => 'ae',
                'name' => 'Avestan',
                'nativeName' => 'avesta',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            12 => 
            array (
                'langcode' => 'ay',
                'name' => 'Aymara',
                'nativeName' => 'aymar aru',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            13 => 
            array (
                'langcode' => 'az',
                'name' => 'Azerbaijani',
                'nativeName' => 'azərbaycan dili',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            14 => 
            array (
                'langcode' => 'bm',
                'name' => 'Bambara',
                'nativeName' => 'bamanankan',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            15 => 
            array (
                'langcode' => 'ba',
                'name' => 'Bashkir',
                'nativeName' => 'башҡорт теле',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            16 => 
            array (
                'langcode' => 'eu',
                'name' => 'Basque',
                'nativeName' => 'euskara, euskera',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            17 => 
            array (
                'langcode' => 'be',
                'name' => 'Belarusian',
                'nativeName' => 'Беларуская',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            18 => 
            array (
                'langcode' => 'bn',
                'name' => 'Bengali',
                'nativeName' => 'বাংলা',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            19 => 
            array (
                'langcode' => 'bh',
                'name' => 'Bihari',
                'nativeName' => 'भोजपुरी',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            20 => 
            array (
                'langcode' => 'bi',
                'name' => 'Bislama',
                'nativeName' => 'Bislama',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            21 => 
            array (
                'langcode' => 'bs',
                'name' => 'Bosnian',
                'nativeName' => 'bosanski jezik',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            22 => 
            array (
                'langcode' => 'br',
                'name' => 'Breton',
                'nativeName' => 'brezhoneg',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            23 => 
            array (
                'langcode' => 'bg',
                'name' => 'Bulgarian',
                'nativeName' => 'български език',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            24 => 
            array (
                'langcode' => 'my',
                'name' => 'Burmese',
                'nativeName' => 'ဗမာစာ',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            25 => 
            array (
                'langcode' => 'ca',
                'name' => 'Catalan; Valencian',
                'nativeName' => 'Català',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            26 => 
            array (
                'langcode' => 'ch',
                'name' => 'Chamorro',
                'nativeName' => 'Chamoru',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            27 => 
            array (
                'langcode' => 'ce',
                'name' => 'Chechen',
                'nativeName' => 'нохчийн мотт',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            28 => 
            array (
                'langcode' => 'ny',
                'name' => 'Chichewa; Chewa; Nyanja',
                'nativeName' => 'chiCheŵa, chinyanja',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            29 => 
            array (
                'langcode' => 'zh',
                'name' => 'Chinese',
            'nativeName' => '中文 (Zhōngwén), 汉语, 漢語',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            30 => 
            array (
                'langcode' => 'cv',
                'name' => 'Chuvash',
                'nativeName' => 'чӑваш чӗлхи',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            31 => 
            array (
                'langcode' => 'kw',
                'name' => 'Cornish',
                'nativeName' => 'Kernewek',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            32 => 
            array (
                'langcode' => 'co',
                'name' => 'Corsican',
                'nativeName' => 'corsu, lingua corsa',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            33 => 
            array (
                'langcode' => 'cr',
                'name' => 'Cree',
                'nativeName' => 'ᓀᐦᐃᔭᐍᐏᐣ',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            34 => 
            array (
                'langcode' => 'hr',
                'name' => 'Croatian',
                'nativeName' => 'hrvatski',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            35 => 
            array (
                'langcode' => 'cs',
                'name' => 'Czech',
                'nativeName' => 'česky, čeština',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            36 => 
            array (
                'langcode' => 'da',
                'name' => 'Danish',
                'nativeName' => 'dansk',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            37 => 
            array (
                'langcode' => 'dv',
                'name' => 'Divehi; Dhivehi; Maldivian;',
                'nativeName' => 'ދިވެހި',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            38 => 
            array (
                'langcode' => 'nl',
                'name' => 'Dutch',
                'nativeName' => 'Nederlands, Vlaams',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            39 => 
            array (
                'langcode' => 'en',
                'name' => 'English',
                'nativeName' => 'English',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            40 => 
            array (
                'langcode' => 'eo',
                'name' => 'Esperanto',
                'nativeName' => 'Esperanto',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            41 => 
            array (
                'langcode' => 'et',
                'name' => 'Estonian',
                'nativeName' => 'eesti, eesti keel',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            42 => 
            array (
                'langcode' => 'ee',
                'name' => 'Ewe',
                'nativeName' => 'Eʋegbe',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            43 => 
            array (
                'langcode' => 'fo',
                'name' => 'Faroese',
                'nativeName' => 'føroyskt',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            44 => 
            array (
                'langcode' => 'fj',
                'name' => 'Fijian',
                'nativeName' => 'vosa Vakaviti',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            45 => 
            array (
                'langcode' => 'fi',
                'name' => 'Finnish',
                'nativeName' => 'suomi, suomen kieli',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            46 => 
            array (
                'langcode' => 'fr',
                'name' => 'French',
                'nativeName' => 'français, langue française',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            47 => 
            array (
                'langcode' => 'ff',
                'name' => 'Fula; Fulah; Pulaar; Pular',
                'nativeName' => 'Fulfulde, Pulaar, Pular',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            48 => 
            array (
                'langcode' => 'gl',
                'name' => 'Galician',
                'nativeName' => 'Galego',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            49 => 
            array (
                'langcode' => 'ka',
                'name' => 'Georgian',
                'nativeName' => 'ქართული',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            50 => 
            array (
                'langcode' => 'de',
                'name' => 'German',
                'nativeName' => 'Deutsch',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            51 => 
            array (
                'langcode' => 'el',
                'name' => 'Greek, Modern',
                'nativeName' => 'Ελληνικά',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            52 => 
            array (
                'langcode' => 'gn',
                'name' => 'Guaraní',
                'nativeName' => 'Avañeẽ',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            53 => 
            array (
                'langcode' => 'gu',
                'name' => 'Gujarati',
                'nativeName' => 'ગુજરાતી',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            54 => 
            array (
                'langcode' => 'ht',
                'name' => 'Haitian; Haitian Creole',
                'nativeName' => 'Kreyòl ayisyen',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            55 => 
            array (
                'langcode' => 'ha',
                'name' => 'Hausa',
                'nativeName' => 'Hausa, هَوُسَ',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            56 => 
            array (
                'langcode' => 'he',
            'name' => 'Hebrew (modern)',
                'nativeName' => 'עברית',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            57 => 
            array (
                'langcode' => 'hz',
                'name' => 'Herero',
                'nativeName' => 'Otjiherero',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            58 => 
            array (
                'langcode' => 'hi',
                'name' => 'Hindi',
                'nativeName' => 'हिन्दी, हिंदी',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            59 => 
            array (
                'langcode' => 'ho',
                'name' => 'Hiri Motu',
                'nativeName' => 'Hiri Motu',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            60 => 
            array (
                'langcode' => 'hu',
                'name' => 'Hungarian',
                'nativeName' => 'Magyar',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            61 => 
            array (
                'langcode' => 'ia',
                'name' => 'Interlingua',
                'nativeName' => 'Interlingua',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            62 => 
            array (
                'langcode' => 'id',
                'name' => 'Indonesian',
                'nativeName' => 'Bahasa Indonesia',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            63 => 
            array (
                'langcode' => 'ie',
                'name' => 'Interlingue',
                'nativeName' => 'Originally called Occidental; then Interlingue after WWII',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            64 => 
            array (
                'langcode' => 'ga',
                'name' => 'Irish',
                'nativeName' => 'Gaeilge',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            65 => 
            array (
                'langcode' => 'ig',
                'name' => 'Igbo',
                'nativeName' => 'Asụsụ Igbo',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            66 => 
            array (
                'langcode' => 'ik',
                'name' => 'Inupiaq',
                'nativeName' => 'Iñupiaq, Iñupiatun',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            67 => 
            array (
                'langcode' => 'io',
                'name' => 'Ido',
                'nativeName' => 'Ido',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            68 => 
            array (
                'langcode' => 'is',
                'name' => 'Icelandic',
                'nativeName' => 'Íslenska',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            69 => 
            array (
                'langcode' => 'it',
                'name' => 'Italian',
                'nativeName' => 'Italiano',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            70 => 
            array (
                'langcode' => 'iu',
                'name' => 'Inuktitut',
                'nativeName' => 'ᐃᓄᒃᑎᑐᑦ',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            71 => 
            array (
                'langcode' => 'ja',
                'name' => 'Japanese',
            'nativeName' => '日本語 (にほんご／にっぽんご)',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            72 => 
            array (
                'langcode' => 'jv',
                'name' => 'Javanese',
                'nativeName' => 'basa Jawa',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            73 => 
            array (
                'langcode' => 'kl',
                'name' => 'Kalaallisut, Greenlandic',
                'nativeName' => 'kalaallisut, kalaallit oqaasii',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            74 => 
            array (
                'langcode' => 'kn',
                'name' => 'Kannada',
                'nativeName' => 'ಕನ್ನಡ',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            75 => 
            array (
                'langcode' => 'kr',
                'name' => 'Kanuri',
                'nativeName' => 'Kanuri',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            76 => 
            array (
                'langcode' => 'ks',
                'name' => 'Kashmiri',
                'nativeName' => 'कश्मीरी, كشميري‎',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            77 => 
            array (
                'langcode' => 'kk',
                'name' => 'Kazakh',
                'nativeName' => 'Қазақ тілі',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            78 => 
            array (
                'langcode' => 'km',
                'name' => 'Khmer',
                'nativeName' => 'ភាសាខ្មែរ',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            79 => 
            array (
                'langcode' => 'ki',
                'name' => 'Kikuyu, Gikuyu',
                'nativeName' => 'Gĩkũyũ',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            80 => 
            array (
                'langcode' => 'rw',
                'name' => 'Kinyarwanda',
                'nativeName' => 'Ikinyarwanda',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            81 => 
            array (
                'langcode' => 'ky',
                'name' => 'Kirghiz, Kyrgyz',
                'nativeName' => 'кыргыз тили',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            82 => 
            array (
                'langcode' => 'kv',
                'name' => 'Komi',
                'nativeName' => 'коми кыв',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            83 => 
            array (
                'langcode' => 'kg',
                'name' => 'Kongo',
                'nativeName' => 'KiKongo',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            84 => 
            array (
                'langcode' => 'ko',
                'name' => 'Korean',
            'nativeName' => '한국어 (韓國語), 조선말 (朝鮮語)',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            85 => 
            array (
                'langcode' => 'ku',
                'name' => 'Kurdish',
                'nativeName' => 'Kurdî, كوردی‎',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            86 => 
            array (
                'langcode' => 'kj',
                'name' => 'Kwanyama, Kuanyama',
                'nativeName' => 'Kuanyama',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            87 => 
            array (
                'langcode' => 'la',
                'name' => 'Latin',
                'nativeName' => 'latine, lingua latina',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            88 => 
            array (
                'langcode' => 'lb',
                'name' => 'Luxembourgish, Letzeburgesch',
                'nativeName' => 'Lëtzebuergesch',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            89 => 
            array (
                'langcode' => 'lg',
                'name' => 'Luganda',
                'nativeName' => 'Luganda',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            90 => 
            array (
                'langcode' => 'li',
                'name' => 'Limburgish, Limburgan, Limburger',
                'nativeName' => 'Limburgs',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            91 => 
            array (
                'langcode' => 'ln',
                'name' => 'Lingala',
                'nativeName' => 'Lingála',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            92 => 
            array (
                'langcode' => 'lo',
                'name' => 'Lao',
                'nativeName' => 'ພາສາລາວ',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            93 => 
            array (
                'langcode' => 'lt',
                'name' => 'Lithuanian',
                'nativeName' => 'lietuvių kalba',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            94 => 
            array (
                'langcode' => 'lu',
                'name' => 'Luba-Katanga',
                'nativeName' => NULL,
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            95 => 
            array (
                'langcode' => 'lv',
                'name' => 'Latvian',
                'nativeName' => 'latviešu valoda',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            96 => 
            array (
                'langcode' => 'gv',
                'name' => 'Manx',
                'nativeName' => 'Gaelg, Gailck',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            97 => 
            array (
                'langcode' => 'mk',
                'name' => 'Macedonian',
                'nativeName' => 'македонски јазик',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            98 => 
            array (
                'langcode' => 'mg',
                'name' => 'Malagasy',
                'nativeName' => 'Malagasy fiteny',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            99 => 
            array (
                'langcode' => 'ms',
                'name' => 'Malay',
                'nativeName' => 'bahasa Melayu, بهاس ملايو‎',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            100 => 
            array (
                'langcode' => 'ml',
                'name' => 'Malayalam',
                'nativeName' => 'മലയാളം',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            101 => 
            array (
                'langcode' => 'mt',
                'name' => 'Maltese',
                'nativeName' => 'Malti',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            102 => 
            array (
                'langcode' => 'mi',
                'name' => 'Māori',
                'nativeName' => 'te reo Māori',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            103 => 
            array (
                'langcode' => 'mr',
            'name' => 'Marathi (Marāṭhī)',
                'nativeName' => 'मराठी',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            104 => 
            array (
                'langcode' => 'mh',
                'name' => 'Marshallese',
                'nativeName' => 'Kajin M̧ajeļ',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            105 => 
            array (
                'langcode' => 'mn',
                'name' => 'Mongolian',
                'nativeName' => 'монгол',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            106 => 
            array (
                'langcode' => 'na',
                'name' => 'Nauru',
                'nativeName' => 'Ekakairũ Naoero',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            107 => 
            array (
                'langcode' => 'nv',
                'name' => 'Navajo, Navaho',
                'nativeName' => 'Diné bizaad, Dinékʼehǰí',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            108 => 
            array (
                'langcode' => 'nb',
                'name' => 'Norwegian Bokmål',
                'nativeName' => 'Norsk bokmål',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            109 => 
            array (
                'langcode' => 'nd',
                'name' => 'North Ndebele',
                'nativeName' => 'isiNdebele',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            110 => 
            array (
                'langcode' => 'ne',
                'name' => 'Nepali',
                'nativeName' => 'नेपाली',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            111 => 
            array (
                'langcode' => 'ng',
                'name' => 'Ndonga',
                'nativeName' => 'Owambo',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            112 => 
            array (
                'langcode' => 'nn',
                'name' => 'Norwegian Nynorsk',
                'nativeName' => 'Norsk nynorsk',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            113 => 
            array (
                'langcode' => 'no',
                'name' => 'Norwegian',
                'nativeName' => 'Norsk',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            114 => 
            array (
                'langcode' => 'ii',
                'name' => 'Nuosu',
                'nativeName' => 'ꆈꌠ꒿ Nuosuhxop',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            115 => 
            array (
                'langcode' => 'nr',
                'name' => 'South Ndebele',
                'nativeName' => 'isiNdebele',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            116 => 
            array (
                'langcode' => 'oc',
                'name' => 'Occitan',
                'nativeName' => 'Occitan',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            117 => 
            array (
                'langcode' => 'oj',
                'name' => 'Ojibwe, Ojibwa',
                'nativeName' => 'ᐊᓂᔑᓈᐯᒧᐎᓐ',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            118 => 
            array (
                'langcode' => 'cu',
                'name' => 'Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic',
                'nativeName' => 'ѩзыкъ словѣньскъ',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            119 => 
            array (
                'langcode' => 'om',
                'name' => 'Oromo',
                'nativeName' => 'Afaan Oromoo',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            120 => 
            array (
                'langcode' => 'or',
                'name' => 'Oriya',
                'nativeName' => 'ଓଡ଼ିଆ',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            121 => 
            array (
                'langcode' => 'os',
                'name' => 'Ossetian, Ossetic',
                'nativeName' => 'ирон æвзаг',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            122 => 
            array (
                'langcode' => 'pa',
                'name' => 'Panjabi, Punjabi',
                'nativeName' => 'ਪੰਜਾਬੀ, پنجابی‎',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            123 => 
            array (
                'langcode' => 'pi',
                'name' => 'Pāli',
                'nativeName' => 'पाऴि',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            124 => 
            array (
                'langcode' => 'fa',
                'name' => 'Persian',
                'nativeName' => 'فارسی',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            125 => 
            array (
                'langcode' => 'pl',
                'name' => 'Polish',
                'nativeName' => 'polski',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            126 => 
            array (
                'langcode' => 'ps',
                'name' => 'Pashto, Pushto',
                'nativeName' => 'پښتو',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            127 => 
            array (
                'langcode' => 'pt',
                'name' => 'Portuguese',
                'nativeName' => 'Português',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            128 => 
            array (
                'langcode' => 'qu',
                'name' => 'Quechua',
                'nativeName' => 'Runa Simi, Kichwa',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            129 => 
            array (
                'langcode' => 'rm',
                'name' => 'Romansh',
                'nativeName' => 'rumantsch grischun',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            130 => 
            array (
                'langcode' => 'rn',
                'name' => 'Kirundi',
                'nativeName' => 'kiRundi',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            131 => 
            array (
                'langcode' => 'ro',
                'name' => 'Romanian, Moldavian, Moldovan',
                'nativeName' => 'română',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            132 => 
            array (
                'langcode' => 'ru',
                'name' => 'Russian',
                'nativeName' => 'русский язык',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            133 => 
            array (
                'langcode' => 'sa',
            'name' => 'Sanskrit (Saṁskṛta)',
                'nativeName' => 'संस्कृतम्',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            134 => 
            array (
                'langcode' => 'sc',
                'name' => 'Sardinian',
                'nativeName' => 'sardu',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            135 => 
            array (
                'langcode' => 'sd',
                'name' => 'Sindhi',
                'nativeName' => 'सिन्धी, سنڌي، سندھی‎',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            136 => 
            array (
                'langcode' => 'se',
                'name' => 'Northern Sami',
                'nativeName' => 'Davvisámegiella',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            137 => 
            array (
                'langcode' => 'sm',
                'name' => 'Samoan',
                'nativeName' => 'gagana faa Samoa',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            138 => 
            array (
                'langcode' => 'sg',
                'name' => 'Sango',
                'nativeName' => 'yângâ tî sängö',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            139 => 
            array (
                'langcode' => 'sr',
                'name' => 'Serbian',
                'nativeName' => 'српски језик',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            140 => 
            array (
                'langcode' => 'gd',
                'name' => 'Scottish Gaelic; Gaelic',
                'nativeName' => 'Gàidhlig',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            141 => 
            array (
                'langcode' => 'sn',
                'name' => 'Shona',
                'nativeName' => 'chiShona',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            142 => 
            array (
                'langcode' => 'si',
                'name' => 'Sinhala, Sinhalese',
                'nativeName' => 'සිංහල',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            143 => 
            array (
                'langcode' => 'sk',
                'name' => 'Slovak',
                'nativeName' => 'slovenčina',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            144 => 
            array (
                'langcode' => 'sl',
                'name' => 'Slovene',
                'nativeName' => 'slovenščina',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            145 => 
            array (
                'langcode' => 'so',
                'name' => 'Somali',
                'nativeName' => 'Soomaaliga, af Soomaali',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            146 => 
            array (
                'langcode' => 'st',
                'name' => 'Southern Sotho',
                'nativeName' => 'Sesotho',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            147 => 
            array (
                'langcode' => 'es',
                'name' => 'Spanish; Castilian',
                'nativeName' => 'español, castellano',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            148 => 
            array (
                'langcode' => 'su',
                'name' => 'Sundanese',
                'nativeName' => 'Basa Sunda',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            149 => 
            array (
                'langcode' => 'sw',
                'name' => 'Swahili',
                'nativeName' => 'Kiswahili',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            150 => 
            array (
                'langcode' => 'ss',
                'name' => 'Swati',
                'nativeName' => 'SiSwati',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            151 => 
            array (
                'langcode' => 'sv',
                'name' => 'Swedish',
                'nativeName' => 'svenska',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            152 => 
            array (
                'langcode' => 'ta',
                'name' => 'Tamil',
                'nativeName' => 'தமிழ்',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            153 => 
            array (
                'langcode' => 'te',
                'name' => 'Telugu',
                'nativeName' => 'తెలుగు',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            154 => 
            array (
                'langcode' => 'tg',
                'name' => 'Tajik',
                'nativeName' => 'тоҷикӣ, toğikī, تاجیکی‎',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            155 => 
            array (
                'langcode' => 'th',
                'name' => 'Thai',
                'nativeName' => 'ไทย',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            156 => 
            array (
                'langcode' => 'ti',
                'name' => 'Tigrinya',
                'nativeName' => 'ትግርኛ',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            157 => 
            array (
                'langcode' => 'bo',
                'name' => 'Tibetan Standard, Tibetan, Central',
                'nativeName' => 'བོད་ཡིག',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            158 => 
            array (
                'langcode' => 'tk',
                'name' => 'Turkmen',
                'nativeName' => 'Türkmen, Түркмен',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            159 => 
            array (
                'langcode' => 'tl',
                'name' => 'Tagalog',
                'nativeName' => 'Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            160 => 
            array (
                'langcode' => 'tn',
                'name' => 'Tswana',
                'nativeName' => 'Setswana',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            161 => 
            array (
                'langcode' => 'to',
            'name' => 'Tonga (Tonga Islands)',
                'nativeName' => 'faka Tonga',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            162 => 
            array (
                'langcode' => 'tr',
                'name' => 'Turkish',
                'nativeName' => 'Türkçe',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            163 => 
            array (
                'langcode' => 'ts',
                'name' => 'Tsonga',
                'nativeName' => 'Xitsonga',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            164 => 
            array (
                'langcode' => 'tt',
                'name' => 'Tatar',
                'nativeName' => 'татарча, tatarça, تاتارچا‎',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            165 => 
            array (
                'langcode' => 'tw',
                'name' => 'Twi',
                'nativeName' => 'Twi',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            166 => 
            array (
                'langcode' => 'ty',
                'name' => 'Tahitian',
                'nativeName' => 'Reo Tahiti',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            167 => 
            array (
                'langcode' => 'ug',
                'name' => 'Uighur, Uyghur',
                'nativeName' => 'Uyƣurqə, ئۇيغۇرچە‎',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            168 => 
            array (
                'langcode' => 'uk',
                'name' => 'Ukrainian',
                'nativeName' => 'українська',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            169 => 
            array (
                'langcode' => 'ur',
                'name' => 'Urdu',
                'nativeName' => 'اردو',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            170 => 
            array (
                'langcode' => 'uz',
                'name' => 'Uzbek',
                'nativeName' => 'zbek, Ўзбек, أۇزبېك‎',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            171 => 
            array (
                'langcode' => 've',
                'name' => 'Venda',
                'nativeName' => 'Tshivenḓa',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            172 => 
            array (
                'langcode' => 'vi',
                'name' => 'Vietnamese',
                'nativeName' => 'Tiếng Việt',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            173 => 
            array (
                'langcode' => 'vo',
                'name' => 'Volapük',
                'nativeName' => 'Volapük',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            174 => 
            array (
                'langcode' => 'wa',
                'name' => 'Walloon',
                'nativeName' => 'Walon',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            175 => 
            array (
                'langcode' => 'cy',
                'name' => 'Welsh',
                'nativeName' => 'Cymraeg',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            176 => 
            array (
                'langcode' => 'wo',
                'name' => 'Wolof',
                'nativeName' => 'Wollof',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            177 => 
            array (
                'langcode' => 'fy',
                'name' => 'Western Frisian',
                'nativeName' => 'Frysk',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            178 => 
            array (
                'langcode' => 'xh',
                'name' => 'Xhosa',
                'nativeName' => 'isiXhosa',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            179 => 
            array (
                'langcode' => 'yi',
                'name' => 'Yiddish',
                'nativeName' => 'ייִדיש',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            180 => 
            array (
                'langcode' => 'yo',
                'name' => 'Yoruba',
                'nativeName' => 'Yorùbá',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
            181 => 
            array (
                'langcode' => 'za',
                'name' => 'Zhuang, Chuang',
                'nativeName' => 'Saɯ cueŋƅ, Saw cuengh',
                'created_by' => 'migration',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
                'list_index' => '1',
            ),
        ));
        
        
    }
}