<?php

namespace Modules\Settings\Database\Seeders;

use Illuminate\Database\Seeder;

class SettingsTimezonesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('settings_timezones')->delete();
        
        \DB::table('settings_timezones')->insert(array (
            0 => 
            array (
                'id' => 1,
                'timezone_abbr' => 'ACDT',
                'timezone_name' => 'Australian Central Daylight Savings',
                'timezone' => 'GMT/UTC +10:30',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'timezone_abbr' => 'ACST',
                'timezone_name' => 'Australian Central Standard',
                'timezone' => 'GMT/UTC +09:30',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'timezone_abbr' => 'ACT',
                'timezone_name' => 'Acre',
                'timezone' => 'GMT/UTC -05:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'timezone_abbr' => 'ACT',
                'timezone_name' => 'ASEAN Common',
                'timezone' => 'GMT/UTC +08:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'timezone_abbr' => 'ADT',
                'timezone_name' => 'Atlantic Daylight',
                'timezone' => 'GMT/UTC -03:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'timezone_abbr' => 'AEDT',
                'timezone_name' => 'Australian Eastern Daylight Savings',
                'timezone' => 'GMT/UTC +11:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'timezone_abbr' => 'AEST',
                'timezone_name' => 'Australian Eastern Standard',
                'timezone' => 'GMT/UTC +10:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'timezone_abbr' => 'AFT',
                'timezone_name' => 'Afghanistan',
                'timezone' => 'GMT/UTC +04:30',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'timezone_abbr' => 'AKDT',
                'timezone_name' => 'Alaska Daylight',
                'timezone' => 'GMT/UTC -08:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'timezone_abbr' => 'AKST',
                'timezone_name' => 'Alaska Standard',
                'timezone' => 'GMT/UTC -09:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'timezone_abbr' => 'AMST',
            'timezone_name' => 'Amazon Summer (Brazil)',
                'timezone' => 'GMT/UTC -03:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'timezone_abbr' => 'AMT',
            'timezone_name' => 'Amazon (Brazil)',
                'timezone' => 'GMT/UTC -04:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'timezone_abbr' => 'AMT',
                'timezone_name' => 'Armenia',
                'timezone' => 'GMT/UTC +04:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'timezone_abbr' => 'ART',
                'timezone_name' => 'Argentina',
                'timezone' => 'GMT/UTC -03:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'timezone_abbr' => 'AST',
                'timezone_name' => 'Arabia Standard',
                'timezone' => 'GMT/UTC +03:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'timezone_abbr' => 'AST',
                'timezone_name' => 'Atlantic Standard',
                'timezone' => 'GMT/UTC -04:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'timezone_abbr' => 'AWDT',
                'timezone_name' => 'Australian Western Daylight',
                'timezone' => 'GMT/UTC +09:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'timezone_abbr' => 'AWST',
                'timezone_name' => 'Australian Western Standard',
                'timezone' => 'GMT/UTC +08:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'timezone_abbr' => 'AZOST',
                'timezone_name' => 'Azores Standard',
                'timezone' => 'GMT/UTC -01:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'timezone_abbr' => 'AZT',
                'timezone_name' => 'Azerbaijan',
                'timezone' => 'GMT/UTC +04:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'timezone_abbr' => 'BDT',
                'timezone_name' => 'Brunei',
                'timezone' => 'GMT/UTC +08:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'timezone_abbr' => 'BDT',
                'timezone_name' => 'Bangladesh Daylight',
                'timezone' => 'GMT/UTC +06:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'timezone_abbr' => 'BIOT',
                'timezone_name' => 'British Indian Ocean',
                'timezone' => 'GMT/UTC +06:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'timezone_abbr' => 'BIT',
                'timezone_name' => 'Baker Island',
                'timezone' => 'GMT/UTC -12:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'timezone_abbr' => 'BOT',
                'timezone_name' => 'Bolivia',
                'timezone' => 'GMT/UTC -04:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'timezone_abbr' => 'BRST',
                'timezone_name' => 'Brasilia Summer',
                'timezone' => 'GMT/UTC -02:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'timezone_abbr' => 'BRT',
                'timezone_name' => 'Brasilia',
                'timezone' => 'GMT/UTC -03:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'timezone_abbr' => 'BST',
                'timezone_name' => 'Bangladesh Standard',
                'timezone' => 'GMT/UTC +06:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'timezone_abbr' => 'BST',
                'timezone_name' => 'Bougainville Standard',
                'timezone' => 'GMT/UTC +11:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'timezone_abbr' => 'BST',
                'timezone_name' => 'British Summer',
                'timezone' => 'GMT/UTC +01:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'timezone_abbr' => 'BTT',
                'timezone_name' => 'Bhutan',
                'timezone' => 'GMT/UTC +06:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'timezone_abbr' => 'CAT',
                'timezone_name' => 'Central Africa',
                'timezone' => 'GMT/UTC +02:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'timezone_abbr' => 'CCT',
                'timezone_name' => 'Cocos Islands',
                'timezone' => 'GMT/UTC +06:30',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'timezone_abbr' => 'CDT',
            'timezone_name' => 'Central Daylight (North America)',
                'timezone' => 'GMT/UTC -05:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'timezone_abbr' => 'CDT',
                'timezone_name' => 'Cuba Daylight',
                'timezone' => 'GMT/UTC -04:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'timezone_abbr' => 'CEDT',
                'timezone_name' => 'Central European Daylight',
                'timezone' => 'GMT/UTC +02:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'timezone_abbr' => 'CEST',
                'timezone_name' => 'Central European Summer',
                'timezone' => 'GMT/UTC +02:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'timezone_abbr' => 'CET',
                'timezone_name' => 'Central European',
                'timezone' => 'GMT/UTC +01:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'timezone_abbr' => 'CHADT',
                'timezone_name' => 'Chatham Daylight',
                'timezone' => 'GMT/UTC +13:45',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'timezone_abbr' => 'CHAST',
                'timezone_name' => 'Chatham Standard',
                'timezone' => 'GMT/UTC +12:45',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'timezone_abbr' => 'CHOT',
                'timezone_name' => 'Choibalsan',
                'timezone' => 'GMT/UTC +08:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'timezone_abbr' => 'ChST',
                'timezone_name' => 'Chamorro Standard',
                'timezone' => 'GMT/UTC +10:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'timezone_abbr' => 'CHUT',
                'timezone_name' => 'Chuuk',
                'timezone' => 'GMT/UTC +10:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'timezone_abbr' => 'CIST',
                'timezone_name' => 'Clipperton Island Standard',
                'timezone' => 'GMT/UTC -08:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'timezone_abbr' => 'CIT',
                'timezone_name' => 'Central Indonesia',
                'timezone' => 'GMT/UTC +08:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'timezone_abbr' => 'CKT',
                'timezone_name' => 'Cook Island',
                'timezone' => 'GMT/UTC -10:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'timezone_abbr' => 'CLST',
                'timezone_name' => 'Chile Summer',
                'timezone' => 'GMT/UTC -03:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'timezone_abbr' => 'CLT',
                'timezone_name' => 'Chile Standard',
                'timezone' => 'GMT/UTC -04:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'timezone_abbr' => 'COST',
                'timezone_name' => 'Colombia Summer',
                'timezone' => 'GMT/UTC -04:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'timezone_abbr' => 'COT',
                'timezone_name' => 'Colombia',
                'timezone' => 'GMT/UTC -05:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'timezone_abbr' => 'CST',
            'timezone_name' => 'Central Standard (North America)',
                'timezone' => 'GMT/UTC -06:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'timezone_abbr' => 'CST',
                'timezone_name' => 'China Standard',
                'timezone' => 'GMT/UTC +08:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'timezone_abbr' => 'CST',
            'timezone_name' => 'Central Standard (Australia)',
                'timezone' => 'GMT/UTC +09:30',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'timezone_abbr' => 'CST',
            'timezone_name' => 'Central Summer (Australia)',
                'timezone' => 'GMT/UTC +10:30',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'timezone_abbr' => 'CST',
                'timezone_name' => 'Cuba Standard',
                'timezone' => 'GMT/UTC -05:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'timezone_abbr' => 'CT',
                'timezone_name' => 'China time',
                'timezone' => 'GMT/UTC +08:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'timezone_abbr' => 'CVT',
                'timezone_name' => 'Cape Verde',
                'timezone' => 'GMT/UTC -01:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'timezone_abbr' => 'CWST',
            'timezone_name' => 'Central Western Standard (Australia) unofficial',
                'timezone' => 'GMT/UTC +08:45',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'timezone_abbr' => 'CXT',
                'timezone_name' => 'Christmas Island',
                'timezone' => 'GMT/UTC +07:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'timezone_abbr' => 'DAVT',
                'timezone_name' => 'Davis',
                'timezone' => 'GMT/UTC +07:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'timezone_abbr' => 'DDUT',
                'timezone_name' => 'Dumont d\'Urville',
                'timezone' => 'GMT/UTC +10:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'timezone_abbr' => 'DFT',
                'timezone_name' => 'AIX specific equivalent of Central European',
                'timezone' => 'GMT/UTC +01:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'timezone_abbr' => 'EASST',
                'timezone_name' => 'Easter Island Standard Summer',
                'timezone' => 'GMT/UTC -05:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'timezone_abbr' => 'EAST',
                'timezone_name' => 'Easter Island Standard',
                'timezone' => 'GMT/UTC -06:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'timezone_abbr' => 'EAT',
                'timezone_name' => 'East Africa',
                'timezone' => 'GMT/UTC +03:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'timezone_abbr' => 'ECT',
                'timezone_name' => 'Eastern Caribbean',
                'timezone' => 'GMT/UTC -04:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'timezone_abbr' => 'ECT',
                'timezone_name' => 'Ecuador',
                'timezone' => 'GMT/UTC -05:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'timezone_abbr' => 'EDT',
            'timezone_name' => 'Eastern Daylight (North America)',
                'timezone' => 'GMT/UTC -04:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'timezone_abbr' => 'EEDT',
                'timezone_name' => 'Eastern European Daylight',
                'timezone' => 'GMT/UTC +03:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'timezone_abbr' => 'EEST',
                'timezone_name' => 'Eastern European Summer',
                'timezone' => 'GMT/UTC +03:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'timezone_abbr' => 'EET',
                'timezone_name' => 'Eastern European',
                'timezone' => 'GMT/UTC +02:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'timezone_abbr' => 'EGST',
                'timezone_name' => 'Eastern Greenland Summer',
                'timezone' => 'GMT/UTC +00:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            72 => 
            array (
                'id' => 73,
                'timezone_abbr' => 'EGT',
                'timezone_name' => 'Eastern Greenland',
                'timezone' => 'GMT/UTC -01:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            73 => 
            array (
                'id' => 74,
                'timezone_abbr' => 'EIT',
                'timezone_name' => 'Eastern Indonesian',
                'timezone' => 'GMT/UTC +09:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            74 => 
            array (
                'id' => 75,
                'timezone_abbr' => 'EST',
            'timezone_name' => 'Eastern Standard (North America)',
                'timezone' => 'GMT/UTC -05:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            75 => 
            array (
                'id' => 76,
                'timezone_abbr' => 'EST',
            'timezone_name' => 'Eastern Standard (Australia)',
                'timezone' => 'GMT/UTC +10:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            76 => 
            array (
                'id' => 77,
                'timezone_abbr' => 'FET',
                'timezone_name' => 'Further-eastern European',
                'timezone' => 'GMT/UTC +03:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            77 => 
            array (
                'id' => 78,
                'timezone_abbr' => 'FJT',
                'timezone_name' => 'Fiji',
                'timezone' => 'GMT/UTC +12:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            78 => 
            array (
                'id' => 79,
                'timezone_abbr' => 'FKST',
                'timezone_name' => 'Falkland Islands Standard',
                'timezone' => 'GMT/UTC -03:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            79 => 
            array (
                'id' => 80,
                'timezone_abbr' => 'FKST',
                'timezone_name' => 'Falkland Islands Summer',
                'timezone' => 'GMT/UTC -03:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            80 => 
            array (
                'id' => 81,
                'timezone_abbr' => 'FKT',
                'timezone_name' => 'Falkland Islands',
                'timezone' => 'GMT/UTC -04:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            81 => 
            array (
                'id' => 82,
                'timezone_abbr' => 'FNT',
                'timezone_name' => 'Fernando de Noronha',
                'timezone' => 'GMT/UTC -02:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            82 => 
            array (
                'id' => 83,
                'timezone_abbr' => 'GALT',
                'timezone_name' => 'Galapagos',
                'timezone' => 'GMT/UTC -06:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            83 => 
            array (
                'id' => 84,
                'timezone_abbr' => 'GAMT',
                'timezone_name' => 'Gambier Islands',
                'timezone' => 'GMT/UTC -09:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            84 => 
            array (
                'id' => 85,
                'timezone_abbr' => 'GET',
                'timezone_name' => 'Georgia Standard',
                'timezone' => 'GMT/UTC +04:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            85 => 
            array (
                'id' => 86,
                'timezone_abbr' => 'GFT',
                'timezone_name' => 'French Guiana',
                'timezone' => 'GMT/UTC -03:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            86 => 
            array (
                'id' => 87,
                'timezone_abbr' => 'GILT',
                'timezone_name' => 'Gilbert Island',
                'timezone' => 'GMT/UTC +12:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            87 => 
            array (
                'id' => 88,
                'timezone_abbr' => 'GIT',
                'timezone_name' => 'Gambier Island',
                'timezone' => 'GMT/UTC -09:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            88 => 
            array (
                'id' => 89,
                'timezone_abbr' => 'GMT',
                'timezone_name' => 'Greenwich Mean',
                'timezone' => 'GMT/UTC 00:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            89 => 
            array (
                'id' => 90,
                'timezone_abbr' => 'GST',
                'timezone_name' => 'South Georgia and the South Sandwich Islands',
                'timezone' => 'GMT/UTC -02:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            90 => 
            array (
                'id' => 91,
                'timezone_abbr' => 'GST',
                'timezone_name' => 'Gulf Standard',
                'timezone' => 'GMT/UTC +04:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            91 => 
            array (
                'id' => 92,
                'timezone_abbr' => 'GYT',
                'timezone_name' => 'Guyana',
                'timezone' => 'GMT/UTC -04:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            92 => 
            array (
                'id' => 93,
                'timezone_abbr' => 'HADT',
                'timezone_name' => 'Hawaii-Aleutian Daylight',
                'timezone' => 'GMT/UTC -09:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            93 => 
            array (
                'id' => 94,
                'timezone_abbr' => 'HAEC',
                'timezone_name' => 'Heure Avancée d\'Europe Centrale',
                'timezone' => 'GMT/UTC +02:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            94 => 
            array (
                'id' => 95,
                'timezone_abbr' => 'HAST',
                'timezone_name' => 'Hawaii-Aleutian Standard',
                'timezone' => 'GMT/UTC -10:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            95 => 
            array (
                'id' => 96,
                'timezone_abbr' => 'HKT',
                'timezone_name' => 'Hong Kong',
                'timezone' => 'GMT/UTC +08:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            96 => 
            array (
                'id' => 97,
                'timezone_abbr' => 'HMT',
                'timezone_name' => 'Heard and McDonald Islands',
                'timezone' => 'GMT/UTC +05:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            97 => 
            array (
                'id' => 98,
                'timezone_abbr' => 'HOVT',
                'timezone_name' => 'Khovd',
                'timezone' => 'GMT/UTC +07:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            98 => 
            array (
                'id' => 99,
                'timezone_abbr' => 'HST',
                'timezone_name' => 'Hawaii Standard',
                'timezone' => 'GMT/UTC -10:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            99 => 
            array (
                'id' => 100,
                'timezone_abbr' => 'IBST',
                'timezone_name' => 'International Business Standard',
                'timezone' => 'GMT/UTC 00:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            100 => 
            array (
                'id' => 101,
                'timezone_abbr' => 'ICT',
                'timezone_name' => 'Indochina',
                'timezone' => 'GMT/UTC +07:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            101 => 
            array (
                'id' => 102,
                'timezone_abbr' => 'IDT',
                'timezone_name' => 'Israel Daylight',
                'timezone' => 'GMT/UTC +03:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            102 => 
            array (
                'id' => 103,
                'timezone_abbr' => 'IOT',
                'timezone_name' => 'Indian Ocean',
                'timezone' => 'GMT/UTC +03:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            103 => 
            array (
                'id' => 104,
                'timezone_abbr' => 'IRDT',
                'timezone_name' => 'Iran Daylight',
                'timezone' => 'GMT/UTC +04:30',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            104 => 
            array (
                'id' => 105,
                'timezone_abbr' => 'IRKT',
                'timezone_name' => 'Irkutsk',
                'timezone' => 'GMT/UTC +08:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            105 => 
            array (
                'id' => 106,
                'timezone_abbr' => 'IRST',
                'timezone_name' => 'Iran Standard',
                'timezone' => 'GMT/UTC +03:30',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            106 => 
            array (
                'id' => 107,
                'timezone_abbr' => 'IST',
                'timezone_name' => 'Indian Standard',
                'timezone' => 'GMT/UTC +05:30',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            107 => 
            array (
                'id' => 108,
                'timezone_abbr' => 'IST',
                'timezone_name' => 'Irish Standard',
                'timezone' => 'GMT/UTC +01:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            108 => 
            array (
                'id' => 109,
                'timezone_abbr' => 'IST',
                'timezone_name' => 'Israel Standard',
                'timezone' => 'GMT/UTC +02:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            109 => 
            array (
                'id' => 110,
                'timezone_abbr' => 'JST',
                'timezone_name' => 'Japan Standard',
                'timezone' => 'GMT/UTC +09:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            110 => 
            array (
                'id' => 111,
                'timezone_abbr' => 'KGT',
                'timezone_name' => 'Kyrgyzstan time',
                'timezone' => 'GMT/UTC +06:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            111 => 
            array (
                'id' => 112,
                'timezone_abbr' => 'KOST',
                'timezone_name' => 'Kosrae',
                'timezone' => 'GMT/UTC +11:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            112 => 
            array (
                'id' => 113,
                'timezone_abbr' => 'KRAT',
                'timezone_name' => 'Krasnoyarsk',
                'timezone' => 'GMT/UTC +07:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            113 => 
            array (
                'id' => 114,
                'timezone_abbr' => 'KST',
                'timezone_name' => 'Korea Standard',
                'timezone' => 'GMT/UTC +09:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            114 => 
            array (
                'id' => 115,
                'timezone_abbr' => 'LHST',
                'timezone_name' => 'Lord Howe Standard',
                'timezone' => 'GMT/UTC +10:30',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            115 => 
            array (
                'id' => 116,
                'timezone_abbr' => 'LHST',
                'timezone_name' => 'Lord Howe Summer',
                'timezone' => 'GMT/UTC +11:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            116 => 
            array (
                'id' => 117,
                'timezone_abbr' => 'LINT',
                'timezone_name' => 'Line Islands',
                'timezone' => 'GMT/UTC +14:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            117 => 
            array (
                'id' => 118,
                'timezone_abbr' => 'MAGT',
                'timezone_name' => 'Magadan',
                'timezone' => 'GMT/UTC +12:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            118 => 
            array (
                'id' => 119,
                'timezone_abbr' => 'MART',
                'timezone_name' => 'Marquesas Islands',
                'timezone' => 'GMT/UTC -09:30',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            119 => 
            array (
                'id' => 120,
                'timezone_abbr' => 'MAWT',
                'timezone_name' => 'Mawson Station',
                'timezone' => 'GMT/UTC +05:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            120 => 
            array (
                'id' => 121,
                'timezone_abbr' => 'MDT',
            'timezone_name' => 'Mountain Daylight (North America)',
                'timezone' => 'GMT/UTC -06:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            121 => 
            array (
                'id' => 122,
                'timezone_abbr' => 'MEST',
                'timezone_name' => 'Middle European Summer Same zone as CEST',
                'timezone' => 'GMT/UTC +02:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            122 => 
            array (
                'id' => 123,
                'timezone_abbr' => 'MET',
                'timezone_name' => 'Middle European Same zone as CET',
                'timezone' => 'GMT/UTC +01:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            123 => 
            array (
                'id' => 124,
                'timezone_abbr' => 'MHT',
                'timezone_name' => 'Marshall Islands',
                'timezone' => 'GMT/UTC +12:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            124 => 
            array (
                'id' => 125,
                'timezone_abbr' => 'MIST',
                'timezone_name' => 'Macquarie Island Station',
                'timezone' => 'GMT/UTC +11:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            125 => 
            array (
                'id' => 126,
                'timezone_abbr' => 'MIT',
                'timezone_name' => 'Marquesas Islands',
                'timezone' => 'GMT/UTC -09:30',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            126 => 
            array (
                'id' => 127,
                'timezone_abbr' => 'MMT',
                'timezone_name' => 'Myanmar',
                'timezone' => 'GMT/UTC +06:30',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            127 => 
            array (
                'id' => 128,
                'timezone_abbr' => 'MSK',
                'timezone_name' => 'Moscow',
                'timezone' => 'GMT/UTC +03:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            128 => 
            array (
                'id' => 129,
                'timezone_abbr' => 'MST',
                'timezone_name' => 'Malaysia Standard',
                'timezone' => 'GMT/UTC +08:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            129 => 
            array (
                'id' => 130,
                'timezone_abbr' => 'MST',
            'timezone_name' => 'Mountain Standard (North America)',
                'timezone' => 'GMT/UTC -07:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            130 => 
            array (
                'id' => 131,
                'timezone_abbr' => 'MST',
                'timezone_name' => 'Myanmar Standard',
                'timezone' => 'GMT/UTC +06:30',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            131 => 
            array (
                'id' => 132,
                'timezone_abbr' => 'MUT',
                'timezone_name' => 'Mauritius',
                'timezone' => 'GMT/UTC +04:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            132 => 
            array (
                'id' => 133,
                'timezone_abbr' => 'MVT',
                'timezone_name' => 'Maldives',
                'timezone' => 'GMT/UTC +05:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            133 => 
            array (
                'id' => 134,
                'timezone_abbr' => 'MYT',
                'timezone_name' => 'Malaysia e',
                'timezone' => 'GMT/UTC +08:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            134 => 
            array (
                'id' => 135,
                'timezone_abbr' => 'NCT',
                'timezone_name' => 'New Caledonia',
                'timezone' => 'GMT/UTC +11:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            135 => 
            array (
                'id' => 136,
                'timezone_abbr' => 'NDT',
                'timezone_name' => 'Newfoundland Daylight',
                'timezone' => 'GMT/UTC -02:30',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            136 => 
            array (
                'id' => 137,
                'timezone_abbr' => 'NFT',
                'timezone_name' => 'Norfolk',
                'timezone' => 'GMT/UTC +11:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            137 => 
            array (
                'id' => 138,
                'timezone_abbr' => 'NPT',
                'timezone_name' => 'Nepal',
                'timezone' => 'GMT/UTC +05:45',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            138 => 
            array (
                'id' => 139,
                'timezone_abbr' => 'NST',
                'timezone_name' => 'Newfoundland Standard',
                'timezone' => 'GMT/UTC -03:30',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            139 => 
            array (
                'id' => 140,
                'timezone_abbr' => 'NT',
                'timezone_name' => 'Newfoundland',
                'timezone' => 'GMT/UTC -03:30',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            140 => 
            array (
                'id' => 141,
                'timezone_abbr' => 'NUT',
                'timezone_name' => 'Niue',
                'timezone' => 'GMT/UTC -11:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            141 => 
            array (
                'id' => 142,
                'timezone_abbr' => 'NZDT',
                'timezone_name' => 'New Zealand Daylight',
                'timezone' => 'GMT/UTC +13:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            142 => 
            array (
                'id' => 143,
                'timezone_abbr' => 'NZST',
                'timezone_name' => 'New Zealand Standard',
                'timezone' => 'GMT/UTC +12:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            143 => 
            array (
                'id' => 144,
                'timezone_abbr' => 'OMST',
                'timezone_name' => 'Omsk',
                'timezone' => 'GMT/UTC +06:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            144 => 
            array (
                'id' => 145,
                'timezone_abbr' => 'ORAT',
                'timezone_name' => 'Oral',
                'timezone' => 'GMT/UTC +05:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            145 => 
            array (
                'id' => 146,
                'timezone_abbr' => 'PDT',
            'timezone_name' => 'Pacific Daylight (North America)',
                'timezone' => 'GMT/UTC -07:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            146 => 
            array (
                'id' => 147,
                'timezone_abbr' => 'PET',
                'timezone_name' => 'Peru',
                'timezone' => 'GMT/UTC -05:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            147 => 
            array (
                'id' => 148,
                'timezone_abbr' => 'PETT',
                'timezone_name' => 'Kamchatka',
                'timezone' => 'GMT/UTC +12:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            148 => 
            array (
                'id' => 149,
                'timezone_abbr' => 'PGT',
                'timezone_name' => 'Papua New Guinea',
                'timezone' => 'GMT/UTC +10:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            149 => 
            array (
                'id' => 150,
                'timezone_abbr' => 'PHOT',
                'timezone_name' => 'Phoenix Island',
                'timezone' => 'GMT/UTC +13:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            150 => 
            array (
                'id' => 151,
                'timezone_abbr' => 'PKT',
                'timezone_name' => 'Pakistan Standard',
                'timezone' => 'GMT/UTC +05:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            151 => 
            array (
                'id' => 152,
                'timezone_abbr' => 'PMDT',
                'timezone_name' => 'Saint Pierre and Miquelon Daylight time',
                'timezone' => 'GMT/UTC -02:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            152 => 
            array (
                'id' => 153,
                'timezone_abbr' => 'PMST',
                'timezone_name' => 'Saint Pierre and Miquelon Standard',
                'timezone' => 'GMT/UTC -03:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            153 => 
            array (
                'id' => 154,
                'timezone_abbr' => 'PONT',
                'timezone_name' => 'Pohnpei Standard',
                'timezone' => 'GMT/UTC +11:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            154 => 
            array (
                'id' => 155,
                'timezone_abbr' => 'PST',
            'timezone_name' => 'Pacific Standard (North America)',
                'timezone' => 'GMT/UTC -08:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            155 => 
            array (
                'id' => 156,
                'timezone_abbr' => 'PST',
                'timezone_name' => 'Philippine Standard',
                'timezone' => 'GMT/UTC +08:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            156 => 
            array (
                'id' => 157,
                'timezone_abbr' => 'PYST',
            'timezone_name' => 'Paraguay Summer (South America)',
                'timezone' => 'GMT/UTC -03:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            157 => 
            array (
                'id' => 158,
                'timezone_abbr' => 'PYT',
            'timezone_name' => 'Paraguay (South America)',
                'timezone' => 'GMT/UTC -04:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            158 => 
            array (
                'id' => 159,
                'timezone_abbr' => 'RET',
                'timezone_name' => 'Réunion',
                'timezone' => 'GMT/UTC +04:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            159 => 
            array (
                'id' => 160,
                'timezone_abbr' => 'ROTT',
                'timezone_name' => 'Rothera Research Station',
                'timezone' => 'GMT/UTC -03:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            160 => 
            array (
                'id' => 161,
                'timezone_abbr' => 'SAKT',
                'timezone_name' => 'Sakhalin Island time',
                'timezone' => 'GMT/UTC +11:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            161 => 
            array (
                'id' => 162,
                'timezone_abbr' => 'SAMT',
                'timezone_name' => 'Samara',
                'timezone' => 'GMT/UTC +04:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            162 => 
            array (
                'id' => 163,
                'timezone_abbr' => 'SAST',
                'timezone_name' => 'South African Standard',
                'timezone' => 'GMT/UTC +02:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            163 => 
            array (
                'id' => 164,
                'timezone_abbr' => 'SBT',
                'timezone_name' => 'Solomon Islands',
                'timezone' => 'GMT/UTC +11:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            164 => 
            array (
                'id' => 165,
                'timezone_abbr' => 'SCT',
                'timezone_name' => 'Seychelles',
                'timezone' => 'GMT/UTC +04:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            165 => 
            array (
                'id' => 166,
                'timezone_abbr' => 'SGT',
                'timezone_name' => 'Singapore',
                'timezone' => 'GMT/UTC +08:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            166 => 
            array (
                'id' => 167,
                'timezone_abbr' => 'SLST',
                'timezone_name' => 'Sri Lanka Standard',
                'timezone' => 'GMT/UTC +05:30',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            167 => 
            array (
                'id' => 168,
                'timezone_abbr' => 'SRET',
                'timezone_name' => 'Srednekolymsk',
                'timezone' => 'GMT/UTC +11:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            168 => 
            array (
                'id' => 169,
                'timezone_abbr' => 'SRT',
                'timezone_name' => 'Suriname',
                'timezone' => 'GMT/UTC -03:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            169 => 
            array (
                'id' => 170,
                'timezone_abbr' => 'SST',
                'timezone_name' => 'Samoa Standard',
                'timezone' => 'GMT/UTC -11:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            170 => 
            array (
                'id' => 171,
                'timezone_abbr' => 'SST',
                'timezone_name' => 'Singapore Standard',
                'timezone' => 'GMT/UTC +08:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            171 => 
            array (
                'id' => 172,
                'timezone_abbr' => 'SYOT',
                'timezone_name' => 'Showa Station',
                'timezone' => 'GMT/UTC +03:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            172 => 
            array (
                'id' => 173,
                'timezone_abbr' => 'TAHT',
                'timezone_name' => 'Tahiti',
                'timezone' => 'GMT/UTC -10:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            173 => 
            array (
                'id' => 174,
                'timezone_abbr' => 'THA',
                'timezone_name' => 'Thailand Standard',
                'timezone' => 'GMT/UTC +07:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            174 => 
            array (
                'id' => 175,
                'timezone_abbr' => 'TJT',
                'timezone_name' => 'Tajikistan',
                'timezone' => 'GMT/UTC +05:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            175 => 
            array (
                'id' => 176,
                'timezone_abbr' => 'TKT',
                'timezone_name' => 'Tokelau',
                'timezone' => 'GMT/UTC +13:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            176 => 
            array (
                'id' => 177,
                'timezone_abbr' => 'TLT',
                'timezone_name' => 'Timor Leste',
                'timezone' => 'GMT/UTC +09:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            177 => 
            array (
                'id' => 178,
                'timezone_abbr' => 'TMT',
                'timezone_name' => 'Turkmenistan',
                'timezone' => 'GMT/UTC +05:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            178 => 
            array (
                'id' => 179,
                'timezone_abbr' => 'TOT',
                'timezone_name' => 'Tonga',
                'timezone' => 'GMT/UTC +13:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            179 => 
            array (
                'id' => 180,
                'timezone_abbr' => 'TVT',
                'timezone_name' => 'Tuvalu',
                'timezone' => 'GMT/UTC +12:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            180 => 
            array (
                'id' => 181,
                'timezone_abbr' => 'UCT',
                'timezone_name' => 'Coordinated Universal',
                'timezone' => 'GMT/UTC 00:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            181 => 
            array (
                'id' => 182,
                'timezone_abbr' => 'ULAT',
                'timezone_name' => 'Ulaanbaatar',
                'timezone' => 'GMT/UTC +08:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            182 => 
            array (
                'id' => 183,
                'timezone_abbr' => 'USZ1',
                'timezone_name' => 'Kaliningrad',
                'timezone' => 'GMT/UTC +02:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            183 => 
            array (
                'id' => 184,
                'timezone_abbr' => 'UTC',
                'timezone_name' => 'Coordinated Universal',
                'timezone' => 'GMT/UTC 00:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            184 => 
            array (
                'id' => 185,
                'timezone_abbr' => 'UYST',
                'timezone_name' => 'Uruguay Summer',
                'timezone' => 'GMT/UTC -02:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            185 => 
            array (
                'id' => 186,
                'timezone_abbr' => 'UYT',
                'timezone_name' => 'Uruguay Standard',
                'timezone' => 'GMT/UTC -03:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            186 => 
            array (
                'id' => 187,
                'timezone_abbr' => 'UZT',
                'timezone_name' => 'Uzbekistan',
                'timezone' => 'GMT/UTC +05:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            187 => 
            array (
                'id' => 188,
                'timezone_abbr' => 'VET',
                'timezone_name' => 'Venezuelan Standard',
                'timezone' => 'GMT/UTC -4:30',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            188 => 
            array (
                'id' => 189,
                'timezone_abbr' => 'VLAT',
                'timezone_name' => 'Vladivostok',
                'timezone' => 'GMT/UTC +10:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            189 => 
            array (
                'id' => 190,
                'timezone_abbr' => 'VOLT',
                'timezone_name' => 'Volgograd',
                'timezone' => 'GMT/UTC +04:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            190 => 
            array (
                'id' => 191,
                'timezone_abbr' => 'VOST',
                'timezone_name' => 'Vostok Station',
                'timezone' => 'GMT/UTC +06:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            191 => 
            array (
                'id' => 192,
                'timezone_abbr' => 'VUT',
                'timezone_name' => 'Vanuatu',
                'timezone' => 'GMT/UTC +11:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            192 => 
            array (
                'id' => 193,
                'timezone_abbr' => 'WAKT',
                'timezone_name' => 'Wake Island',
                'timezone' => 'GMT/UTC +12:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            193 => 
            array (
                'id' => 194,
                'timezone_abbr' => 'WAST',
                'timezone_name' => 'West Africa Summer',
                'timezone' => 'GMT/UTC +02:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            194 => 
            array (
                'id' => 195,
                'timezone_abbr' => 'WAT',
                'timezone_name' => 'West Africa',
                'timezone' => 'GMT/UTC +01:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            195 => 
            array (
                'id' => 196,
                'timezone_abbr' => 'WEDT',
                'timezone_name' => 'Western European Daylight',
                'timezone' => 'GMT/UTC +01:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            196 => 
            array (
                'id' => 197,
                'timezone_abbr' => 'WEST',
                'timezone_name' => 'Western European Summer',
                'timezone' => 'GMT/UTC +01:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            197 => 
            array (
                'id' => 198,
                'timezone_abbr' => 'WET',
                'timezone_name' => 'Western European',
                'timezone' => 'GMT/UTC +00:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            198 => 
            array (
                'id' => 199,
                'timezone_abbr' => 'WIT',
                'timezone_name' => 'Western Indonesian',
                'timezone' => 'GMT/UTC +07:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            199 => 
            array (
                'id' => 200,
                'timezone_abbr' => 'WST',
                'timezone_name' => 'Western Standard',
                'timezone' => 'GMT/UTC +08:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            200 => 
            array (
                'id' => 201,
                'timezone_abbr' => 'YAKT',
                'timezone_name' => 'Yakutsk',
                'timezone' => 'GMT/UTC +09:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            201 => 
            array (
                'id' => 202,
                'timezone_abbr' => 'YEKT',
                'timezone_name' => 'Yekaterinburg',
                'timezone' => 'GMT/UTC +05:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
            202 => 
            array (
                'id' => 203,
                'timezone_abbr' => 'Z',
                'timezone_name' => 'Zulu',
                'timezone' => 'GMT/UTC 00:00',
                'created_by' => NULL,
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => now(),
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}