<?php

namespace Modules\Settings\Database\Seeders;

use Illuminate\Database\Seeder;

class SettingsBarcodeTypesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        // \DB::table('settings_barcode_types')->delete();
        
        \DB::table('settings_barcode_types')->insert(array (
            0 => 
            array (
                'id' => 1,
                'barcodeType' => 'Australia Postal Code',
                'sampleImage' => 'australia-postal-code.png',
                'category' => '2-D',
                'characterSet' => 'Numbers Only',
                'length' => '4',
                'checksum' => 'Required',
                'notes' => 'Includes error correction',
                'created_by' => 'dev',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'barcodeType' => 'Aztec Code',
                'sampleImage' => 'aztec-code.png',
                'category' => '2-D',
                'characterSet' => 'Full ASCII; FNC1 and ESI control codes',
                'length' => 'Variable Min 12 Max 3832',
                'checksum' => 'Required',
                'notes' => 'Includes error correction; minimum is 15x15 square, largest is 151x151',
                'created_by' => 'dev',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'barcodeType' => 'Codabar',
                'sampleImage' => 'codabar.png',
                'category' => 'Linear',
                'characterSet' => 'Numbers: 0-9; Symbols: - : . $ / + Start/Stop Characters: A, B, C, D, E, *, N, or T',
                'length' => 'Variable',
                'checksum' => 'None',
                'notes' => 'Older code; often used in libraries and blood banks. See also USD-4, NW-7, 2of7',
                'created_by' => 'dev',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'barcodeType' => 'Code 11',
                'sampleImage' => 'code-11.png',
                'category' => 'Linear',
                'characterSet' => 'Required',
                'length' => 'Variable',
                'checksum' => 'Numbers Only',
                'notes' => 'Recommend 2nd check digit',
                'created_by' => 'dev',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'barcodeType' => 'Code 128',
                'sampleImage' => 'code-128.png',
                'category' => 'Linear',
                'characterSet' => 'All ASCII characters and control codes',
                'length' => 'Variable',
                'checksum' => 'Required',
                'notes' => 'Widely used; excellent for many applications',
                'created_by' => 'dev',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'barcodeType' => 'Code 39',
                'sampleImage' => 'code-39.png',
                'category' => 'Linear',
                'characterSet' => 'Uppercase letters A-Z; Numbers 0-9; Space - . $ / + %',
                'length' => 'Variable',
                'checksum' => 'Optional',
                'notes' => 'In very wide use for many types of applications',
                'created_by' => 'dev',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'barcodeType' => 'Extended Code 39',
                'sampleImage' => 'extended-code-39.png',
                'category' => 'Linear',
                'characterSet' => 'All ASCII characters and control codes',
                'length' => 'Variable',
                'checksum' => 'Optional',
                'notes' => 'Uses pairs of characters to encode non- standard symbols; wasteful of space',
                'created_by' => 'dev',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'barcodeType' => 'Code 93',
                'sampleImage' => 'code-93.png',
                'category' => 'Linear',
                'characterSet' => 'Uppercase letters A-Z; Numbers 0-9; Space - . $ / + %',
                'length' => 'nbsp',
                'checksum' => 'Optional',
                'notes' => 'A more compact cousin of Code 39, not as widely in use',
                'created_by' => 'dev',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'barcodeType' => 'Composite Code',
                'sampleImage' => 'composite-code.png',
                'category' => '2-D',
                'characterSet' => 'All ASCII characters',
                'length' => 'Variable',
                'checksum' => 'Required',
                'notes' => 'Code comprised of a PDF417 code stacked on top of a Code128; used in UCC/EAN standards',
                'created_by' => 'dev',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'barcodeType' => 'DataMatrix',
                'sampleImage' => 'datamatrix.png',
                'category' => '2-D',
                'characterSet' => 'All ASCII characters',
                'length' => 'Variable',
                'checksum' => 'Required',
                'notes' => 'Includes error correction, up to 2335 ASCII characters',
                'created_by' => 'dev',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'barcodeType' => 'EAN-13',
                'sampleImage' => 'ean-13.png',
                'category' => 'Linear',
                'characterSet' => 'Numbers Only',
                'length' => '13 + check digit +2 optional +5 optional',
                'checksum' => 'Required',
                'notes' => 'Retail product marking world-wide',
                'created_by' => 'dev',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'barcodeType' => 'EAN-8',
                'sampleImage' => 'ean-8.png',
                'category' => 'Linear',
                'characterSet' => 'Numbers Only',
                'length' => '7 + check digit',
                'checksum' => 'Required',
                'notes' => 'Retail product marking world-wide; compressed code for products with limited label space',
                'created_by' => 'dev',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'barcodeType' => 'UPC-A',
                'sampleImage' => 'upc-a.png',
                'category' => 'Linear',
                'characterSet' => '11 + check digit +2 optional +5 optional',
                'length' => 'Numbers Only',
                'checksum' => 'Required',
                'notes' => 'Retail product marking in USA and Canada',
                'created_by' => 'dev',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'barcodeType' => 'QR Code',
                'sampleImage' => 'qr-code.png',
                'category' => '2-D',
                'characterSet' => 'All ASCII characters',
                'length' => 'Variable',
                'checksum' => 'Required',
                'notes' => 'Includes error correction, up to about 1520 ASCII or 2509 numeric charcters',
                'created_by' => 'dev',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'barcodeType' => 'Industrial 2 of 5',
                'sampleImage' => 'industrial-2-5.png',
                'category' => 'Linear',
                'characterSet' => 'Numbers Only',
                'length' => 'Variable',
                'checksum' => 'None',
                'notes' => 'Older type of code',
                'created_by' => 'dev',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'barcodeType' => 'Interleaved 2 of 5',
                'sampleImage' => 'interleaved-2-5.png',
                'category' => 'Linear',
                'characterSet' => 'Numbers Only',
                'length' => 'Variable',
                'checksum' => 'Optional',
                'notes' => 'Very compact encodes digits in pairs so total length must be even number of digits',
                'created_by' => 'dev',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'barcodeType' => 'ITF-14',
                'sampleImage' => 'itf-14.png',
                'category' => 'Linear',
                'characterSet' => 'Numbers Only',
                'length' => '13 + check digit',
                'checksum' => 'Required',
            'notes' => 'Special use of the Interleaved 2 of 5 code to mark shipping cartons containing UPC encoded products (see also SCC-14)',
                'created_by' => 'dev',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'barcodeType' => 'Maxicode',
                'sampleImage' => 'maxicode.png',
                'category' => '2-D',
                'characterSet' => 'All ASCII characters',
                'length' => '93',
                'checksum' => 'Required',
                'notes' => 'Includes error correction, developed by the United Parcel Service for encoding destination information',
                'created_by' => 'dev',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'barcodeType' => 'MSI MSI Plessey',
                'sampleImage' => 'msi-msi-plessey.png',
                'category' => 'Linear',
                'characterSet' => 'Numbers Only',
                'length' => 'Variable',
                'checksum' => 'Required',
                'notes' => 'Grocery store shelf tags',
                'created_by' => 'dev',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'barcodeType' => 'PDF-417',
                'sampleImage' => 'pdf-417.png',
                'category' => '2-D',
                'characterSet' => 'All ASCII characters',
                'length' => 'Variable',
                'checksum' => 'Required',
                'notes' => 'Includes error correction, up to about 1850 ASCII or 2725 numeric characters',
                'created_by' => 'dev',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'barcodeType' => 'Plessey',
                'sampleImage' => 'plessey.png',
                'category' => 'Linear',
                'characterSet' => 'Numbers Only',
                'length' => 'Variable',
                'checksum' => 'Required',
                'notes' => 'Grocery store shelf tags',
                'created_by' => 'dev',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'barcodeType' => 'Postnet',
                'sampleImage' => 'postnet.png',
                'category' => '2-D',
                'characterSet' => 'Numbers Only',
                'length' => '5 + check digit +4 optional +6 optional',
                'checksum' => 'Required',
            'notes' => 'USA postal code (ZIP code)',
                'created_by' => 'dev',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
            'barcodeType' => 'SCC-14 (UCC/EAN Ship Cont. Code)',
                'sampleImage' => 'scc-14.png',
                'category' => 'Linear',
                'characterSet' => 'Numbers Only',
                'length' => '13 + checksum',
                'checksum' => 'Required',
            'notes' => 'Special use of Code 128 to mark shipping cartons containing UPC encoded products (see also ITF-14)',
                'created_by' => 'dev',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'barcodeType' => 'Standard 2 of 5',
                'sampleImage' => 'standard-2-5.png',
                'category' => 'Linear',
                'characterSet' => 'Numbers Only',
                'length' => 'Variable',
                'checksum' => 'None',
                'notes' => 'Also called Industrial 2 of 5.',
                'created_by' => 'dev',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'barcodeType' => 'UCC/EAN-128',
                'sampleImage' => 'ucc-ean-128.png',
                'category' => 'Linear',
                'characterSet' => 'All ASCII characters and control codes',
                'length' => 'Variable',
                'checksum' => 'Required',
                'notes' => 'Special ise of Code 128 which defines data formats for commerce',
                'created_by' => 'dev',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
            'barcodeType' => 'UCC/EAN Shipping Container Code (SCC-14)',
                'sampleImage' => 'ucc-ean-shipping.png',
                'category' => 'Linear',
                'characterSet' => 'Numbers Only',
                'length' => '13 + check digit',
                'checksum' => 'Required',
            'notes' => 'Special use of the Interleaved 2 of 5 code to mark shipping cartons containing UPC encoded products (see also SCC-14)',
                'created_by' => 'dev',
                'modified_by' => NULL,
                'enabled' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}